### ISSUE TITLE
[BUG] TideBit-Lagacy matching 出錯，導致 matching 流程沒有完成，使得頁面不會更新

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1007]
- 經檢查 matching 出錯的原因是
```
I, [2022-11-02T18:01:49.618528 #9122] 
 INFO -- : #<OrderBid id: 122, bid: 34, ask: 2, currency: 201, price: #<BigDecimal:7f6831605ab8,'0.21531195E5',18(27)>, volume: #<BigDecimal:7f6831605928,'0.4702E-4',9(18)>, origin_volume: #<BigDecimal:7f6831605798,'0.1E-2',9(18)>, state: 100, done_at: nil, type: "OrderBid", member_id: 13, created_at: "2022-10-31 09:13:51", updated_at: "2022-10-31 09:13:51", sn: nil, source: "Web", ord_type: nil, locked: #<BigDecimal:7f6831604398,'0.198891063E1',18(27)>, origin_locked: #<BigDecimal:7f6831604118,'0.21531195E2',18(27)>, funds_received: #<BigDecimal:7f6832b9bf58,'0.95298E-3',9(18)>, trades_count: 1>
/home/ubuntu/TideBit-Lagacy/app/models/matching/order_book_manager.rb:13:in `build_order': Missing ord_type: {:id=>122, :market=>"btcusdt", :type=>:bid, :ord_type=>nil, :volume=>#<BigDecimal:7f6831605928,'0.4702E-4',9(18)>, :price=>#<BigDecimal:7f6831605ab8,'0.21531195E5',18(27)>, :locked=>#<BigDecimal:7f6831604398,'0.198891063E1',18(27)>, :timestamp=>1667207631} (ArgumentError)
	from /home/ubuntu/TideBit-Lagacy/app/models/worker/matching.rb:64:in `build_order'
```
- 在DB裡找到這個 order  
![Image](https://user-images.githubusercontent.com/17249354/199636457-90be914e-70ff-4e59-a881-3a4ea507e5b9.png)

那這個 order 的狀態是不對的，因為沒有是 OKX 的 ioc 類型交易，應該是 `立即成交并取消剩余` 不會停留在waiting，並且有對應完成的 outer_trades 紀錄

![Image](https://user-images.githubusercontent.com/17249354/199636807-848910c3-f20f-4de7-8873-f38c78ee171b.png)

![Image](https://user-images.githubusercontent.com/17249354/199636911-08887bb1-cd0b-403a-8b09-cd8d715d429f.png)

- 解決方案

直接到 DB 改這個 order 的狀態從 `state 100`改成 `state 200` 重啟matching daemon

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221111.md)驗證成功
