### ISSUE TITLE
[BUG] 直接打開交易頁面或是直接刷新交易頁面會出現空白畫面

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1009]
- 錯誤原因是為了在 #980 可以使用 `tickerBook` 裡面 `getPrice` 的功能，將前端啟動的流程 `storeCtx.init` 及 `storeCtx.start`從原本由一個component呼叫，改成拆開來分別由兩個 component 各自呼叫，原本的作法可以保障 `storeCtx.init` 完成後才會呼叫 `storeCtx.start`，而新的作法會導致直接打開交易頁面的時候會出現`storeCtx.init`還沒完成就呼叫`storeCtx.start`有些值(ex. getTickers 還沒完成所以沒有對應的 tickers )還不存在所以出錯
- 解決方案
  - 在 `storeProvider` 裡面加上 `isInit`的 state， 讓另一個 component 可以知道 init 是否已完成，並在會導致頁面空白的原因 `TradeForm` 裡面用到 `storeCtx.selectedTicker.last` 加上訪呆

**Comment by Julian0701** [comment]
使用[TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000006_%E4%BA%A4%E6%98%93%E7%95%8C%E9%9D%A2%E7%9A%84%E5%8D%B3%E6%99%82%E6%9B%B4%E6%96%B0%E6%AA%A2%E9%A9%97.md)驗證

**Comment by TzuHanLiang** [comment]
take 2hr

**Comment by Julian0701** [comment]
於[TBETC000006 交易界面的即時更新](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000006/20221104.md
)驗證通過
