### ISSUE TITLE
[BUG] /analysis 頁面的table 上顯示更多的邏輯調整 - 搓合成交紀錄 

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1012]
- 將顯示更多改成分頁

**Comment by TzuHanLiang** [comment]
- take 3hrs

**Comment by TzuHanLiang** [comment]
remain 3hr
- 切分 api
撮合成交紀錄 圖表 api
撮合成交紀錄 總盈利 api

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by TzuHanLiang** [comment]
> remain 3hr
> 
> * 切分 api
>   撮合成交紀錄 圖表 api
>   撮合成交紀錄 總盈利 api

#1034

**Comment by Julian0701** [comment]
使用[TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000009_%E7%AE%A1%E7%90%86%E5%93%A1%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000001 撮合成交紀錄查詢](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000001/20221111.md)驗證通過
