### ISSUE TITLE
[BUG] /analysis 頁面的table 上顯示更多的邏輯調整 - 當前掛單紀錄 

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1013]
- 將顯示更多改成分頁

**Comment by TzuHanLiang** [comment]
take 2hrs

**Comment by Julian0701** [comment]
使用[TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000009_%E7%AE%A1%E7%90%86%E5%93%A1%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by TzuHanLiang** [comment]
- remain 頁數調整 1hr 用 DB 問

**Comment by TzuHanLiang** [comment]
- take 1hr

**Comment by Julian0701** [comment]
於[TBETC000009 管理員介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20221111.md)驗證不通過

**Comment by TzuHanLiang** [comment]
@Julian0701 @Luphia  當前掛單紀錄的上一頁不為 disable 是因為與 @Luphia  討論過後同意，當前掛單紀錄的上一頁要可以去問最新紀錄 UX 的部分如果需要調整的話，需要進一步協助

**Comment by TzuHanLiang** [comment]
- 經討論後決定 disable  上一頁

**Comment by TzuHanLiang** [comment]
- take 1hrs

**Comment by Julian0701** [comment]
於[TBETC000009 管理員介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20221125.md)驗證不通過
