### ISSUE TITLE
[BUG] 當前掛單紀錄的異常交易標示有誤

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBitEx#1014]
- 測試環境
  - MacBook Pro
  - MacOS 13.0
  - Chrome

![image](https://user-images.githubusercontent.com/114177573/199871270-923d39e5-891b-4033-ad68-dc8a84049a12.png)

- 下面兩筆交易沒有 TideBit 的資料，應出現紅底表示。
- 上面一筆交易的 OKX 和 TideBit 看起來一致，卻被標示異常。

**Comment by TzuHanLiang** [comment]
> * 測試環境
>   
>   * MacBook Pro
>   * MacOS 13.0
>   * Chrome
> 
> ![image](https://user-images.githubusercontent.com/114177573/199871270-923d39e5-891b-4033-ad68-dc8a84049a12.png)
> 
> * 下面兩筆交易沒有 TideBit 的資料，應出現紅底表示。 
> * 上面一筆交易的 OKX 和 TideBit 看起來一致，卻被標示異常。

* 下面兩筆交易沒有 TideBit 的資料，應出現紅底表示。  是因為測試環境DB被我清空過，所以會沒有對應的資料
* * 上面一筆交易的 OKX 和 TideBit 看起來一致，卻被標示異常。 是因為TideBit 紀錄的 `狀態` 與OKx 紀錄的 `狀態` 不一致 => 更新介面

**Comment by Julian0701** [comment]
使用[TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000009_%E7%AE%A1%E7%90%86%E5%93%A1%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000009 管理員介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20221111.md)驗證通過
