### ISSUE TITLE
[Bug] 撮合交易紀錄顯示手續費有誤

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitEx#1026]
- Test Environment
```
2022-11-07 10:51:19
MacBook Pro
MacOS 13.0
Chrome 13.0
```

- How To Reproduce
```
Login with admin account
access https://www.tidebit.com/analysis
click hamburger menu
click 營收管理
click 撮合成交記錄查詢
choose BTC-USDT
find the record of 11/03 
```

- Exception Description
```
The result is different with OKX API https://www.okx.com/api/v5/trade/fills
```

- Expect Result
```
The Fee of OKX must be same with OKX API https://www.okx.com/api/v5/trade/fills
For example, transaction fee of trade ID 381937828 is -0.00001134713
```

- Refference
[Fill Data of OKX](https://github.com/CAFECA-IO/TideBitEx/files/9947900/1103OKX.txt)
<img width="1381" alt="TideBitAnalysis" src="https://user-images.githubusercontent.com/270062/200221464-72c66474-42aa-471e-a33e-b6393dd90686.png">

**Comment by TzuHanLiang** [comment]
- take 1hr

db: outer_trades 紀錄的 data 有兩種來源 okx 的 order 及 okx 的 trade
來源為 okx 的 order 時 fee 要使用 fillFee 不是 fee（[因為fee 在 order 裡面是累計的 fee](https://www.okx.com/docs-v5/zh/#websocket-api-private-channel-order-channel)）
<img width="539" alt="Screen Shot 2022-11-07 at 18 51 53" src="https://user-images.githubusercontent.com/17249354/200292846-4251b147-27f1-478f-985a-f1d8f57dfd2c.png">
<img width="541" alt="Screen Shot 2022-11-07 at 18 52 01" src="https://user-images.githubusercontent.com/17249354/200292853-aeb52aa3-78e4-4b84-bc19-1947489f9912.png">

**Comment by Julian0701** [comment]
於[TBETC000001 撮合成交紀錄查詢](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000001/20221111.md)驗證通過
