### ISSUE TITLE
[Enhance] 新增 API： 撮合成交紀錄圖表 api

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1034]
- 要將查詢過的資料存在 storage
- 將查詢區間的撮合成交紀錄整理成圖表可以的資料格式
- 計算查詢區間的總獲利
- 後端實作匯率查詢

**Comment by TzuHanLiang** [comment]
- take 4.5hrs

**Comment by TzuHanLiang** [comment]
> * take 4.5hrs
> * https://test.tidebit.network/api/v1/trade/profits?instId=BTC-USDT&exchange=OKEx&start=2022-10-11&end=2022-11-10

- LTC-USDT 有錯誤 remain 1hr

**Comment by Julian0701** [comment]
使用[TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000009_%E7%AE%A1%E7%90%86%E5%93%A1%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000001 撮合成交紀錄查詢](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000001/20221111.md)驗證通過
