### ISSUE TITLE
[ENHANCE] 新增table： outer_orders

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1039]
- 目的：
  - 實作 /analysis 當前掛單紀錄 分頁
- 作法：
  - 定期sync [Get order List - Retrieve all incomplete orders under the current account.](GET /api/v5/trade/orders-pending)
  - DB 保持與 api 一致，沒有的新增，有的刪除
  - id 使用 exchangeCode + orderId

**Comment by TzuHanLiang** [comment]
- take 3hrs

**Comment by Julian0701** [comment]
使用 [TBETC000012](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000012_%20Tidebit%20database%20%E4%BD%BF%E7%94%A8%E6%83%85%E5%BD%A2.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000012](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000012/20221216.md) 驗證通過
