### ISSUE TITLE
[BUG] accountVersion table created_at 及 updated_at 紀錄錯誤

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1040]
![Image](https://user-images.githubusercontent.com/17249354/201007499-1a83c10a-e4d8-4368-b002-52a67890a0de.png)

**Comment by TzuHanLiang** [comment]
- insert sql 格式錯誤 take 2hr
- pr #1033

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221111.md)驗證成功
