### ISSUE TITLE
[BUG] order 可以重複 canceled

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1041]
可以重複 cancel order

**Comment by TzuHanLiang** [comment]
- 解法：
- 簡化 cancal order 傳送的參數，避免出現資料填錯卻cancel 成功的情況

- take 2hr 
- pr #1033

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221111.md)驗證不通過

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221202.md)驗證不通過
出現一筆無法取消的委託單
