### ISSUE TITLE
[BUG] 平台資產總覽過濾錯誤

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1042]
- 過濾按鈕按下後實際產出的資料與期望不符

**Comment by Julian0701** [comment]
使用[TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000009_%E7%AE%A1%E7%90%86%E5%93%A1%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000009 管理員介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20221111.md)驗證通過
