### ISSUE TITLE
[BUG] 平台資產總覽應該要能看到 TideBit 的資產

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBitEx#1048]
- 測試環境
  - MacBook Pro
  - MacOS 13.0
  - Chrome

- 應該要跟 OKx 一樣顯示總資產，但目前 TideBit 的資產都是空的

![image](https://user-images.githubusercontent.com/114177573/201270381-552cd22e-bf04-44a0-ac62-025c45675f4a.png)

**Comment by TzuHanLiang** [comment]
- 使用 asset_balance 的資料

**Comment by TzuHanLiang** [comment]
take 1.5hrs

**Comment by Julian0701** [comment]
使用 [TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000009_%E7%AE%A1%E7%90%86%E5%93%A1%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20221216.md) 驗證通過
