### ISSUE TITLE
[BUG] 用戶 accessyu422@gmail.com 反饋 BTC & ETH 不能自行取消掛單，看數據庫確實有三個訂單是wait，但是有兩個訂單應該是部分成交了。需確認可能原因。

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1059]
accessyu422@gmail.com

(A.)Order 無法取消
1)一張ETHHKD的order(ID:399183101,交易量:5)無法取消.

(B.)Order 成交錯誤數目
2) order(ID:398931123) 下單0.1 BTC，成交了 0.14 BTC

(C.)BTC,ETH鎖定數量不正確
1)ETH鎖定數量錯誤顯示為4.2. (但未成交的是5 ETH，並且取消不了)
2)BTC鎖定數量錯誤顯示為-0.15xxxxxxxxxxxx (沒有未成交 --> 只有 order(ID:398931123) 下單0.1 BTC，成交了 0.14 BTC --> 但顯示未成交)

**Comment by TzuHanLiang** [comment]
<img width="603" alt="Screen Shot 2022-11-16 at 00 47 00" src="https://user-images.githubusercontent.com/17249354/201977796-e30e6452-35a3-4ef0-add9-6bfec5741218.png"
<img width="604" alt="Screen Shot 2022-11-16 at 00 47 30" src="https://user-images.githubusercontent.com/17249354/201977892-7d3c848d-cbc7-4701-a919-0f49d505920b.png">
>
<img width="609" alt="Screen Shot 2022-11-16 at 00 49 11" src="https://user-images.githubusercontent.com/17249354/201978238-78943eeb-7dde-44ee-8ea2-60a0d9c589c2.png">

<img width="1459" alt="Screen Shot 2022-11-16 at 00 49 37" src="https://user-images.githubusercontent.com/17249354/201978347-4cf2788e-1ae2-4702-a296-8ec128e433f3.png">
<img width="1460" alt="Screen Shot 2022-11-16 at 00 50 02" src="https://user-images.githubusercontent.com/17249354/201978450-9901585c-b74e-4628-8b20-c2fb429b5e39.png">

<img width="1456" alt="Screen Shot 2022-11-16 at 00 50 16" src="https://user-images.githubusercontent.com/17249354/201978511-28b4a7ac-a21e-4f6a-a73d-ac746d014d08.png">

**Comment by TzuHanLiang** [comment]
(B.)Order 成交錯誤數目
- 錯誤出現的原因為重複處理的 order 原本流程有漏洞，並且沒有檢驗機制導致重複處理

**Comment by TzuHanLiang** [comment]
<img width="714" alt="Screen Shot 2022-11-16 at 10 18 35" src="https://user-images.githubusercontent.com/17249354/202067498-85743ed5-e2d0-4151-bfa1-b82f6dd491de.png">

**Comment by TzuHanLiang** [comment]
- take 5hrs

**Comment by TzuHanLiang** [comment]
- remain
  - 檢查是否還有其餘異常的 orders

**Comment by TzuHanLiang** [comment]
- 已檢查，現在應該是可以直接透過 /analysis 頁面看出 orders 是否有異常

**Comment by TzuHanLiang** [comment]
- take 1hrs

**Comment by Julian0701** [comment]
使用 [TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221125.md) 驗證通過
