### ISSUE TITLE
[BUG] /analysis 撮合成交紀錄上有多筆異常的 outerTrade 且異常情況不完全與 DB 紀錄情況一致

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1063]
- 調整 /analysis 撮合成交紀錄用到的 api 
  - outerTrade 對應的 DB 資料，如 order 及 voucher 還是直接到 DB取得，不使用 outer_trades table 上的資料（因為更新流程目前有問題，outer_trades table上的資料不齊全）
  - 在頁面上新增欄位 state 
    - 若我們DB紀錄的訂單狀態與 okx 不同 如#1061 #1062  的情況就可以在 /analysis 撮合成交紀錄 上看出來

**Comment by TzuHanLiang** [comment]
- take 3hr

**Comment by Julian0701** [comment]
於 [TBETC000001](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000001/20221125.md) 驗證通過
