### ISSUE TITLE
[BUG] 處理連續撮合或是連續處理多筆撮合的時候，用戶餘額會出現更新錯誤

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1065]
1. 第一種情況是 DB table 的欄位沒有 locked，應使用 `SELECT * FROM accounts WHERE id = ? FOR UPDATE`
2. 在 ExchangeServicesHub sync 的時候會用 for loop 連續處理多筆撮合紀錄， for loop 的 await 沒有寫好，實際上沒有等上一筆完成就call 下一筆

**Comment by TzuHanLiang** [comment]
> take 5hrs
> 
> * 第一種情況
>   
>   * [參考](https://kknews.cc/zh-tw/code/3apjm2a.html) 這邊使用的是悲觀鎖
>   * 更新 accounts 及 orders 的table 時使用的行所(有指定 primary key）
> * 第二種情況
>   
>   * 在ExchangeHub 新增 worker 處理
>   * 每當有需要處理的撮合紀錄，將其先丟到 queue 裡，再由worker 定期去檢查是否有需要處理的紀錄，有就處理，沒有就休息一下後處理

- select for update 的 raw query 不能直接用在 sequelize lib，目前使用 sequelize lib 提供的 lock option

**Comment by TzuHanLiang** [comment]
- select for update 的 raw query  範例
```
       BEGIN;
       SELECT
       	balance,
       	locked,
       	updated_at
       FROM
       	accounts
       WHERE
         id = 3
       FOR UPDATE;
       UPDATE
       	accounts
       SET
         balance = 27920.072959, locked = 0.001, updated_at = "2022-11-18T12:41:47.973Z"
       WHERE
         id = 3;
       COMMIT;
```

**Comment by Julian0701** [comment]
使用 [TBETC000010](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000010_%E6%92%AE%E5%90%88%E6%88%90%E4%BA%A4%E5%BE%8C%E9%A4%98%E9%A1%8D%E6%9B%B4%E6%96%B0%E9%A9%97%E8%AD%89.md) 驗證

**Comment by Julian0701** [comment]
- 觀察至 2 月底沒有重現的錯誤，驗證通過
