### ISSUE TITLE
[ENHANCE] 新增API：fixAbnormalAccounut

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1069]
## 用來更新餘額異常的 account 並新增稽核紀錄
-  select * from accounts for update
  -  檢查是否需要更新
-  insert audit record
-  update account

**Comment by TzuHanLiang** [comment]
- take 3hrs

**Comment by TzuHanLiang** [comment]
- remain 修改紀錄記在另一張table上 fixed_account_record #1104

**Comment by TzuHanLiang** [comment]
take 1 hrs

**Comment by Julian0701** [comment]
使用 [TBETC000012_ Tidebit database 使用情形](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000012_%20Tidebit%20database%20%E4%BD%BF%E7%94%A8%E6%83%85%E5%BD%A2.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000012](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000012/20221209.md) 驗證通過
