### ISSUE TITLE
[ENHANCE] 新首頁/整個網站 自動登出

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1084]
- 新增首頁後 peatio session 的機制就沒有作用了，要把原本做在 /markets 頁面的自動登出，搬移到首頁，且刪除用戶資料（這個之前沒做）

**Comment by TzuHanLiang** [comment]
take 3hrs
- 在backend 呼叫 signout 無法將user 登出，即時更新 user的 cookie
- 改成直接在前端呼叫tidebit 的api

**Comment by Julian0701** [comment]
於 [TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000006/20221223.md) 驗證通過
