### ISSUE TITLE
[BUG] 前端會送重複的 events

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1087]
在 send ws request 失敗後前端會一直嘗試重試發生同樣的request， 如ws斷線後
<img width="660" alt="Screen Shot 2022-11-25 at 14 40 45" src="https://user-images.githubusercontent.com/17249354/203916636-6360997e-f350-428d-91a4-9ae433f73df8.png">

**Comment by TzuHanLiang** [comment]
take 1.5hrs

**Comment by Julian0701** [comment]
使用 [TBETC000011_ WebSocket 頻寬使用情形](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000011_%20WebSocket%20%E9%A0%BB%E5%AF%AC%E4%BD%BF%E7%94%A8%E6%83%85%E5%BD%A2.md)驗證

**Comment by Julian0701** [comment]
於 [TBETC000011](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000011/20221202.md) 驗證通過
