### ISSUE TITLE
[BUG] 撮和成交記錄的翻頁功能在切換交易對和顯示過濾時會有問題

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBitEx#1099]
- 測試環境
    - MacBook Pro
    - MacOS 13.0
    - Chrome
- 在 ETH/USDT 點擊顯示近一年的資料，之後再切換到 BTC/USDT ，顯示的資料仍是近 30 日的，而且翻頁也會出問題
- 詳細見[螢幕錄製](https://drive.google.com/file/d/1yE3n6JmKLpfyhOQS1uw3K4VWhxcAgjbV/view?usp=share_link)

**Comment by TzuHanLiang** [comment]
take 1hr

**Comment by Julian0701** [comment]
使用 [TBETC000001_撮合成交紀錄查詢](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000001_%E6%92%AE%E5%90%88%E6%88%90%E4%BA%A4%E7%B4%80%E9%8C%84%E6%9F%A5%E8%A9%A2.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000001](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000001/20221209.md) 驗證通過
