### ISSUE TITLE
[ENHANCE] 實作 okx request 頻率限制，request 超過限制應等待

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1105]
不同 api 頻率限制不一樣，具體根據 api 文件說明
- [Get order history (last 7 days）](https://www.okx.com/docs-v5/en/#rest-api-trade-get-order-history-last-7-days) Rate Limit: 40 requests per 2 seconds

**Comment by Julian0701** [comment]
使用 [TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000006_%E4%BA%A4%E6%98%93%E7%95%8C%E9%9D%A2%E7%9A%84%E5%8D%B3%E6%99%82%E6%9B%B4%E6%96%B0%E6%AA%A2%E9%A9%97.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000006/20221216.md) 驗證通過
