### ISSUE TITLE
[BUG] 當前掛單紀錄 ETH/USDT 的顯示過濾出現異常

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBitEx#1109]
- 測試環境 https://test.tidebit.network/
    - MacBook Pro
    - MacOS 13.0
    - Chrome
 
![image](https://user-images.githubusercontent.com/114177573/206632681-b7521078-815c-452d-8fbe-3353d7209ba6.png)
![image](https://user-images.githubusercontent.com/114177573/206633896-e5c49b2a-33aa-4737-9dde-ee3754ec1ba7.png)
- 點擊賣出記錄第一頁卻是空的，翻到第二頁才看到內容

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by Julian0701** [comment]
使用 [TBETC000009_管理員介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000009_%E7%AE%A1%E7%90%86%E5%93%A1%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md) 驗證

**Comment by Julian0701** [comment]
改為使用 [TBETC000013_當前掛單記錄查詢](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000013_%E7%95%B6%E5%89%8D%E6%8E%9B%E5%96%AE%E8%A8%98%E9%8C%84%E6%9F%A5%E8%A9%A2.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000013](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000013/20230217.md) 驗證通過
