### ISSUE TITLE
[BUG] 首頁的 ticker 價格走勢圖有時會不見

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1115]
- 問題出現的原因是當切換 ticker 時會取消對應的 market 監聽，當首頁的監聽的 ticker 被切換時會觸法取消監聽，所以走勢圖會不見

**Comment by TzuHanLiang** [comment]
- take 1hrs

**Comment by Julian0701** [comment]
使用 [TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000006_%E4%BA%A4%E6%98%93%E7%95%8C%E9%9D%A2%E7%9A%84%E5%8D%B3%E6%99%82%E6%9B%B4%E6%96%B0%E6%AA%A2%E9%A9%97.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000006/20221216.md) 驗證通過
