### ISSUE TITLE
[BUG] /markets 頁面更新後的 UserInfo 沒有給初始值會無法顯示 account 列表

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1117]
- 用 useEffect 給初始值
- 更新 css 加上 pointer

**Comment by TzuHanLiang** [comment]
take 1hr

**Comment by Julian0701** [comment]
使用 [TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000006_%E4%BA%A4%E6%98%93%E7%95%8C%E9%9D%A2%E7%9A%84%E5%8D%B3%E6%99%82%E6%9B%B4%E6%96%B0%E6%AA%A2%E9%A9%97.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000006/20221216.md) 驗證通過
