### ISSUE TITLE
[BUG] 完善在前端註冊首頁監聽ticker的流程

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1118]
- 有 storeProvider 裡面定義的 registerMarkets 來決定首頁監聽哪些ticker 
  - 不限於 OKx ticker

**Comment by TzuHanLiang** [comment]
- take 1hr

**Comment by Julian0701** [comment]
使用 [TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000006_%E4%BA%A4%E6%98%93%E7%95%8C%E9%9D%A2%E7%9A%84%E5%8D%B3%E6%99%82%E6%9B%B4%E6%96%B0%E6%AA%A2%E9%A9%97.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000006/20221216.md) 驗證通過
