### ISSUE TITLE
[Enhance] 移除 digital_staking 連結

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1120]
受到監管要求，TideBit 需取消 staking 功能，需關閉以下 digital_staking 入口：
  - 首頁（web/mobile）
  - 用戶登錄後頁面（my account）：需要在 TideBit-Lagacy 專案中移除
  - market 頁面

**Comment by TzuHanLiang** [comment]
take 1hr

**Comment by Julian0701** [comment]
使用 [TBETC000003](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000003_%E4%BD%BF%E7%94%A8%E8%80%85%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000003](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000003/20221216.md) 驗證通過

**Comment by Julian0701** [comment]
https://staging-001.tidebit.network/ 的連結還未移除
[TBETC000003](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000003/20221223.md)

**Comment by Julian0701** [comment]
於 [TBETC000003_使用者介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000003/20230119.md) 驗證通過
