### ISSUE TITLE
[BUG] 當前掛單資料有缺

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1133]
- DB 內為 waiting 狀態的 order 沒有出現在當前掛單頁面

- [x] 補上 DB waiting 狀態的 order
- [x] DB waiting 的 order 要的第三方 library 找相關紀錄（可能是canceled）

**Comment by TzuHanLiang** [comment]
- take 3hrs

**Comment by Julian0701** [comment]
使用 [TBETC000013_當前掛單記錄查詢](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000013_%E7%95%B6%E5%89%8D%E6%8E%9B%E5%96%AE%E8%A8%98%E9%8C%84%E6%9F%A5%E8%A9%A2.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000013](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000013/20230106.md) 驗證通過
