### ISSUE TITLE
[BUG] members fix account 失敗沒有正確顯示

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1136]
- [x] fix account api 呼叫失敗後畫面還是秀 success，需要顯示失敗

**Comment by TzuHanLiang** [comment]
- fixed by #1195

**Comment by Julian0701** [comment]
使用 [TBETC000009_管理員介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000009_%E7%AE%A1%E7%90%86%E5%93%A1%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20230210.md) 驗證通過
