### ISSUE TITLE
[BUG] 更新 accounts table 值的紀錄辦法

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1137]
- [x] 先 insertAccountVersion
- [x] 使用 sum(account_versions.balance) 來更新 account table balance
- [x] 使用 sum(account_versions.locked) 來更新 account table locked
- [x] 通知前端的值要根據 accounts table 的值

ref: [link](https://stackoverflow.com/questions/7030699/oracle-sql-update-a-table-with-data-from-another-table)
```
UPDATE table1 account
   SET (balance, locked) = (
   		SELECT sum(balance) as balance, sum(locked) as locked, count(*)
			FROM account_versions
			WHERE account_id = 42108
			Group By account_id
	)
WHERE account_id = 42108
```

**Comment by TzuHanLiang** [comment]
- take 3hrs

**Comment by TzuHanLiang** [comment]
實際使用的 sql 語法
```
UPDATE
	accounts
SET
	balance = (
		SELECT
			sum(balance)
		FROM
			account_versions
		WHERE
			account_versions.account_id = 1856038), LOCKED = (
			SELECT
				sum(LOCKED)
			FROM
				account_versions
			WHERE
				account_versions.account_id = 1856038), updated_at = "2022-12-23T12:00:30.283Z"
		WHERE
			id = 1856038
		LIMIT 1;
```

**Comment by Julian0701** [comment]
於 [TBETC000010_撮合成交後餘額更新驗證](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000010/20230119.md) 驗證通過
