### ISSUE TITLE
[BUG] 立即推薦的頁面無法捲動

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBitEx#1140]
- 測試環境 https://staging-001.tidebit.network/referrals
    - MacBook Pro
    - MacOS 13.0
    - Chrome

https://user-images.githubusercontent.com/114177573/209267920-7b9e376a-20bb-4a82-875a-4629d4c94d44.mov

如影片所示，立即推薦的頁面無法往下捲動

**Comment by TzuHanLiang** [comment]
- take 1hr

**Comment by Julian0701** [comment]
於 [TBETC000007_推薦人交易回饋功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000007/20230119.md) 驗證通過
