### ISSUE TITLE
[UI] TBD- Share failed

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/TideBitEx#1141]
補分享失敗反饋畫面

**Comment by JodieWu** [comment]
完成時間：0.5 hr

Mobile
https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/

Web
https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/

**Comment by Luphia** [comment]
- 需補充取消分享畫面

**Comment by JodieWu** [comment]
完成時間：1 hr
https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/6c88ee36-1689-4dde-8346-c8409e757105/
