### ISSUE TITLE
[BUG] getTrades error 有拿到 data 但是卻顯示error

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1146]
- 在 首頁 及 交易頁面均會出現

**Comment by TzuHanLiang** [comment]
take 1hr

**Comment by Julian0701** [comment]
於 [TBETC000006_交易界面的即時更新檢驗](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000006/20230119.md) 驗證通過
