### ISSUE TITLE
[BUG] v0.8.23.1 /analysis 部分功能無法使用

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBitEx#1161]
- 測試環境 https://staging-001.tidebit.network/analysis
    - MacBook Pro
    - MacOS 13.0
    - Chrome

如[錄影](https://drive.google.com/file/d/1B4f3TbbnYQvRs2eVP-rPM8tsPoLk7gc3/view?usp=share_link)所示，調整手續費 和 新增/刪除管理員 等會跳出窗口的功能都沒有反應，但 switch 功能是正常的

**Comment by TzuHanLiang** [comment]
take 2 hrs

**Comment by Julian0701** [comment]
於 [TBETC000004_出入金手續費管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000004/20230119.md) 驗證通過
