### ISSUE TITLE
[BUG] 撮和成交紀錄的關鍵字搜尋功能異常

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBitEx#1162]
- 測試環境 https://staging-001.tidebit.network/analysis
    - MacBook Pro
    - MacOS 13.0
    - Chrome

- 如[錄影](https://drive.google.com/file/d/1oghlz4qCbMxoGzevRd7ZAwRU_XBUq1yJ/view?usp=share_link)所示，關鍵字搜尋在 BTC/USDT 可以運作，但切到 ETH/HKD 就會進入一直加載的狀態。重新整理後再填入關鍵字則沒有任何反應
- 進行本測試時 BTC/HKD 交易對本來就沒有資料

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by Julian0701** [comment]
於 [TBETC000001_撮合成交紀錄查詢](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000001/20230119.md) 驗證不通過
