### ISSUE TITLE
[BUG] 註冊的驗證機器人失效

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBitEx#1163]
- 測試環境 https://staging-001.tidebit.network/analysis
    - MacBook Pro
    - MacOS 13.0
    - Chrome
   
![image](https://user-images.githubusercontent.com/114177573/210968667-476d0f24-cfd5-4dad-93bd-17153a374d29.png)

**Comment by TzuHanLiang** [comment]
take 1hr

**Comment by Julian0701** [comment]
於 [TBETC000002_管理權限帳號](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000002/20230119.md) 驗證通過
