### ISSUE TITLE
[BUG] Okx ticker 下委託單是我們系統出現重複紀錄委託的情況

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1166]
<img width="1680" alt="Screen Shot 2023-01-10 at 21 16 55" src="https://user-images.githubusercontent.com/17249354/211562988-2754bb1d-2435-49bb-9d62-b04e9b1f35e2.png">
<img width="1680" alt="Screen Shot 2023-01-10 at 21 17 10" src="https://user-images.githubusercontent.com/17249354/211563027-ab6144b6-ae39-4073-b83e-ad8d66ab5d0a.png">

**Comment by TzuHanLiang** [comment]
postPlaceOrder 
```
flowchart TD
    subgraph postPlaceOrder
    A(start)-->D{source}
    D-->|OKX|B[_getPlaceOrderData]
    D-->|TideBit|E[tidebit connector post order]
    E-->|reuslt|Y[return post order reuslt]
    B-->C[database insertOrder]
    C-->F{has no error?}
    F-->|YES|G[database update Account and insert accVersion]
    F-->|NO, post order fail|Y
    G-->H{has no error?}
    H-->|YES|I[post order on okx]
    H-->|NO, post order fail|Y
    I-->J{success?}
    J-->K[inform frontend order success]
    K-->|post order success|Y
    J-->L[cancelDBOrderHandler]
    L-->M{success?}
    M-->|YES|N[inform frontend order canceled]
    N-->|post order success|Y
    Y-->Z(end)
    end
```
![postPlaceOrder](https://user-images.githubusercontent.com/17249354/213158855-a3dfeef8-6d59-480c-88f4-851679240056.svg)

**Comment by TzuHanLiang** [comment]
- 測試無再現且目前沒有再現的方法

**Comment by Julian0701** [comment]
- 觀察至 2 月底都沒有發生錯誤重現，驗證通過
