### ISSUE TITLE
[TEST] database 卡住

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1168]
#1159 問題可能是因為 DB 被鎖造成的，所以將 mySql 的 function 全部補上 countdown 看是否有 DB 卡住的問題

**Comment by TzuHanLiang** [comment]
take 5hrs
一開始 function調整的方向耦合性過高，後經討論改寫成另一種形式

**Comment by TzuHanLiang** [comment]
> <img alt="Screen Shot 2023-01-12 at 19 11 19" width="970" src="https://user-images.githubusercontent.com/17249354/212054265-1809737c-f031-4446-9ebe-c0b4c4618c52.png">
> 
> 一個價格合適的委託單，一委託就被成功撮合

如果同時發生多筆這樣的委託，就可能導致系統crash

**Comment by TzuHanLiang** [comment]
- take 3hrs 
- [ ] check insertOrder、getOrder、getTradeByTradeFk 花時間的原因
- [ ] optimize getTradeByTradeFk query --> 原本 >10s 現在 < 1s

**Comment by Julian0701** [comment]
於 [TBETC000003_使用者介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000003/20230119.md) 驗證通過

**Comment by Julian0701** [comment]
- 觀察至 2 月底沒有異常情形發生，驗證通過
