### ISSUE TITLE
[BUG] 移除個人帳戶和登入頁面還有數位理財的連結

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1176]
![Image](https://user-images.githubusercontent.com/17249354/213057469-0344e248-a532-4e0f-a645-70e8c0df01de.png)

**Comment by TzuHanLiang** [comment]
關聯 #1120 

需要移除 digital_staking 連結相關的頁面
```
vi app/views/shared/_header_home.html.slim 
vi app/views/application/_header_sidebar.html.slim 
vi app/views/application/_header.html.slim 
vi app/views/private/markets/show.mobile.html.slim 
```

**Comment by TzuHanLiang** [comment]
take 1hr

**Comment by Julian0701** [comment]
於 [TBETC000003_使用者介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000003/20230119.md) 驗證通過
