### ISSUE TITLE
[BUG] TidebitEx OKx 委託單資料格式少了 tag

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1187]
- 已修正：錯誤為 class property 名稱錯誤，錯將 this.okexBrokerId 用成 this.brokerId
 - [PR](https://github.com/CAFECA-IO/TideBitEx/pull/1181) 要依據 [PR 規範更新](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/code-review.md) 修改

**Comment by TzuHanLiang** [comment]
- take 1hrs

**Comment by Julian0701** [comment]
- 預計觀察至月底

**Comment by Julian0701** [comment]
無異常情形發生，驗證通過
