### ISSUE TITLE
[BUG] 撮合成交紀錄查詢頁面的錯字

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBitEx#1194]
- 測試環境 https://staging-001.tidebit.network/analysis
- 測試版本 v0.8.23.5
    - MacBook Pro
    - MacOS 13.0
    - Chrome

![image](https://user-images.githubusercontent.com/114177573/216551628-8431f931-572c-4562-8f4f-fd9a32878c8a.png)

- 應該是「撮」

**Comment by TzuHanLiang** [comment]
- take 1hrs

**Comment by Julian0701** [comment]
使用 [TBETC000001_撮合成交紀錄查詢](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000001_%E6%92%AE%E5%90%88%E6%88%90%E4%BA%A4%E7%B4%80%E9%8C%84%E6%9F%A5%E8%A9%A2.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000001](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000001/20230210.md) 驗證通過
