### ISSUE TITLE
[Bug] Audit failure

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitEx#1195]
# Environment
- Machine: iMac Pro 2017
- OS: macOS Ventura v13.1
- Browser: Google Chrome v109.0.5414.119
# How to reproduce

# Current Result
- accountId 1592326 USDT amount will be fix to 0
- USDT amount was not fixed after clicking fixed button
<img width="826" alt="截圖 2023-02-04 上午11 05 54" src="https://user-images.githubusercontent.com/270062/216744045-febdb569-1ff8-4cbf-b82e-c87e533ab10b.png">

# Expect Result
- USDT amount should be fix to 2321.120254286
- USDT amount should be fixed to expected amount after clicking fixed button

**Comment by TzuHanLiang** [comment]
- take 1hrs

**Comment by Julian0701** [comment]
使用 [TBETC000009_管理員介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000009_%E7%AE%A1%E7%90%86%E5%93%A1%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20230210.md) 驗證不通過

**Comment by Julian0701** [comment]
![image](https://user-images.githubusercontent.com/114177573/219559293-720f07a1-2020-4061-b918-f9f8ca36befe.png)

- 資產可以修正了，但訊息欄的內容有誤
