### ISSUE TITLE
[BUG] websocket 傳過來的 canceled order 沒有 kind(bid | ask) 參數

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1214]
- 在 okex postOrder 失敗後也會紀錄 DB 且會紀錄為 canceled 並透過 websocket 通知前端
- 在頁面刷新後剛剛失敗而取消的 order 會顯示正確的 kind 代表 DB 紀錄正確

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by Julian0701** [comment]
使用 [TBETC000005_撮合交易功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20230217.md) 驗證通過
