### ISSUE TITLE
OKX getOrderList params error

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#1235]
OKX getOrderList param 有兩處錯誤 ， 根據[ okx api](https://www.okx.com/docs-v5/en/#rest-api-trade-get-order-list) 文件 Get order List ( 取得 pending order）
      - limit 上限為 100 （原本寫 1000）
      - state 原本寫 'OPEN' and 'CLOSE' 但實際上 state 只能填寫 live, partially_filled 導致
<img width="1680" alt="Screenshot 2023-03-08 at 15 09 36" src="https://user-images.githubusercontent.com/17249354/223644862-e001e9b5-4d9a-4fb9-a67b-cc6a1504c720.png">

**Comment by TzuHanLiang** [comment]
take 1hrs

**Comment by Julian0701** [comment]
觀察到下週(3/17)

**Comment by Julian0701** [comment]
本週系統發生異常，延長觀察到 3/31

**Comment by Julian0701** [comment]
沒有出現異常的交易，驗證通過
