### ISSUE TITLE
[UI Update] 多語系

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#133]
- 先加 中文

**Comment by Luphia** [comment]
- English
- 简体中文
- 繁體中文

**Comment by TzuHanLiang** [comment]
take 4.5hrs

**Comment by Luphia** [comment]
需使用以下 cookie 內參數自動選擇語系
document.cookie.split(';').find(v => /lang/.test(v))?.split('=')[1]

若上述參數不存在則使用以下參數
navigator.language

用戶選擇後須在 cookie 進行如下操作
document.cookie = "lang=zh-TW"

**Comment by Luphia** [comment]
- still happened with windows system

**Comment by TzuHanLiang** [comment]
-take another 5hrs （debug cookie duplicate lang and fix lang button empty issue)
total 10hrs
