### ISSUE TITLE
[UI Update] 沒有顯示 TideBit-Legacy 上的 MarketPairs

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#139]
目前只支援 okex 的交易對，要補上 Tibe-legacy的交易對

**Comment by Luphia** [comment]
- require backend api (trading pair in TideBit-Legacy)

**Comment by TzuHanLiang** [comment]
3hrs

**Comment by TzuHanLiang** [comment]
<img width="419" alt="Screen Shot 2022-03-04 at 7 12 02 PM" src="https://user-images.githubusercontent.com/17249354/156753256-e3a708d1-97ae-44f9-ad94-78e57645b2ef.png">
