### ISSUE TITLE
Trading Pair API with OKEx and TideBit pairs

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/TideBitEx#151]
撈取DB
過濾跟OKEX重複的交易對
註記交易對來源
- TIDEBIT 上有且 OKEx 上也有 -> 使用 OKEx
- OKEx 上有，TideBit 上沒有 -> 不顯示

**Comment by Waiting4Ever** [comment]
在tidebit legacy的XSRF-TOKEN應該有個產生規則，產生出來的X-CSRF-Token可以正常使用

測試步驟：
1. 進入legacy舊交易介面
2. 開啟web tool監聽network
3. 輸入價格：2000、數量：2
4. 點選買入
5. 檢查Name: order_bids的header跟payload
6. 複製網址、Cookie、X-CSRF-Token進postman
7. 複製form-data，修改價格：1000、數量：3、total：3000
8. 送出檢查結果是否是
```json
{
    "result": true,
    "message": "Success"
}
```

**Comment by Luphia** [comment]
Fixed with #217
