### ISSUE TITLE
Favicon and Title for Trading page

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitEx#154]
- current
<img width="239" alt="截圖 2022-03-02 下午6 58 14" src="https://user-images.githubusercontent.com/270062/156349092-5a924533-7e74-4b50-8f19-3dc4424ae372.png">

- should be
<img width="229" alt="截圖 2022-03-02 下午6 58 01" src="https://user-images.githubusercontent.com/270062/156349103-f5da504f-2452-4f16-a7d5-5221e4f17ace.png">

**Comment by TzuHanLiang** [comment]
15 mins
