### ISSUE TITLE
建立交易紀錄 trades

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/TideBitEx#172]
table trades建立新的交易紀錄

**Comment by Waiting4Ever** [comment]
發現裡面有兩個 foreign key 
- ask_member_id
- bid_member_id from member

**Comment by Waiting4Ever** [comment]
考慮到這個table的用途
可能是撮合引擎建立撮合交易紀錄用的，而交易本身我們轉交給okex後不會用到
我主張跳過這個table，但仍須跟香港確認

**Comment by Luphia** [comment]
- require system member
- If it is trading with OKEx user, Trades.ask_member_id or Trades.bid_member_id = system member
- work around: skip this step

**Comment by TzuHanLiang** [comment]
- fixed by #688
