### ISSUE TITLE
UX Research [User story-日本]

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitEx#196]
以創建的Persona 延展出 Epic 再延展出包含 Find/Engage/Comeback/Refer 等 User story

**Comment by JodieWu** [comment]
完成時間：2 hr
https://drive.google.com/file/d/1rnQCzgAEJzCxI31jXyAZ7n2TjOmgEkQx/view?usp=sharing

**Comment by Luphia** [comment]
- 不符合此階段 TA
- 參考需求：高收入避稅

**Comment by JodieWu** [comment]
已修改完畢
修改時間 1.5 hr
