### ISSUE TITLE
WebSocket 整合

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitEx#220]
- 接收來自 OKEx 與 TideBit Slanger 的資訊
- 統一整理為 TideBit Slanger 的格式發送
- TideBitEx 前端接收 WebSocket 資料格式調整

**Comment by TzuHanLiang** [comment]
- 4/6 [TideBit Slanger 的資料格式整理](https://github.com/CAFECA-IO/TideBitEx/wiki/WebSocket-from-TideBit---Legacy) take 8hrs [unfinished, 一共有6種event，其中有四種的回傳格式未知，並且沒有javascript 可以用的sample code]

**Comment by TzuHanLiang** [comment]
- 4/7 在 TideBitEx 上串接上 TideBit-Legacy  pusher（public channel）， private channel authenticate 未解決，出現getMemberIdFromRedis parse Latin1 error。 take 8hrs

**Comment by TzuHanLiang** [comment]
- 4/8  
  - 在 TideBitEx 上串接上 TideBit-Legacy pusher (both public & private)
  - websocket 格式修改改了 Tickers & orders
- 預計剩餘
  - TideBit-Legacy account websocket 串接 1-2hrs
  - TideBit-Legacy trade websocket 串接 1-2hrs

**Comment by TzuHanLiang** [comment]
功能均已實作，並且功能正常， #276  接手
