### ISSUE TITLE
[UX] Wireframe- Finance

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/TideBitEx#242]
買幣/換幣/提現之交易頁面Wireframe

**Comment by JodieWu** [comment]
完成時間：6 hr
https://xd.adobe.com/view/f4ee3151-c011-48d8-98ff-de53ea76780d-a1bd/

**Comment by Luphia** [comment]
reconfirm
- trading history
- consumer dispute solution
- payment solution
