### ISSUE TITLE
[BUG][UI] Okex TradingChart realtime update

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#319]
- 根據每筆新增的 trades 去更新舊的bar 或是畫新的 bar
-  在 Tidebit-Legacy/public/tradingview/datafeed.js
  - TradingViewChart 內部呼叫 subscribeBars ， 觸發 Tidebit-Legacy/public/tradingview/streaming.js 裡面的 subscribeOnStream
- subscribeOnStream call connect 以建立 websocket (const socket = new WebSocket(`wss://${window.location.host}`);) 連線，開始監聽 trades 更新

**Comment by TzuHanLiang** [comment]
take 5hr

**Comment by Luphia** [comment]
pull request
