### ISSUE TITLE
[Branding] Logo Redesign 製作

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/TideBitEx#321]
舊logo轉電子檔

**Comment by JodieWu** [comment]
完成時間：2 hr
https://drive.google.com/drive/folders/18-yBRu1Sg6Agyzvvv_GGa-7_pkRSyKDA?usp=sharing

**Comment by Luphia** [comment]
需補上 Logo 使用說明文件

**Comment by JodieWu** [comment]
已另外新增票 https://github.com/CAFECA-IO/TideBitEx/issues/295#issue-1213844189
