### ISSUE TITLE
DB Traffic issue

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitEx#332]
## 使用功能

Login 和 交易

## 狀況重現步驟
1. 首次登入進入Trading 頁面
2. 進行多次限價單買進
3. 刷新頁面
4. 登入出錯
5. 查看 log
6. log-> DB traffic issue
## 期待結果
保持登入狀態

## 實際結果
1. 進行多次交易時會出現沒有登入的狀態（如下圖）
2. 連續登入登出會出現沒有登入的狀態 （如下圖）

![](https://i.imgur.com/wwI6Sw2.png)

**Comment by TzuHanLiang** [comment]
[解決方案]
- 檢查使用到sql transaction 的部份是否有確實在行為結束時執行 commit，在行為失敗時執行 rollback。
- DB連線，實作connection pool，目前使用的library為[sequelize](https://www.npmjs.com/search?q=sequelize)，在new Sequelize 加上 pool相關的參數。

**Comment by TzuHanLiang** [comment]
take 2hrs

**Comment by royal0721** [comment]
> take 2hrs 已修正一版，待重測 @royal0721

早上測試 ok ,  待下午重新測試
