### ISSUE TITLE
Incorrect MyOrder list issue

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitEx#333]
## 使用功能
買進賣出 和 取消交易

## 狀況重現步驟
1. 已入金使用者登入
2. 進入 Trading 頁面
3. Ｍy Orders 中的 Open Orders 交易單無法取消
4. My Orders 中顯示的交易單為其他使用者的交易單

## 期待結果
MyOrder list 正確顯示該使用者的交易單

## 實際結果
因為交易單並非該使用者的交易單，故取消失敗（如下圖）

![](https://i.imgur.com/egc1pph.png)

**Comment by TzuHanLiang** [comment]
[解決方案]
原先是為了減少DB query ，所以將 memberId 寫在 TidebitConnector，所以導致現在這個issue ，所以不將 memberId 寫在 TidebitConnector ，改將每次交易或是取消交易是會去query currency的id 寫在TidebitConnector

**Comment by TzuHanLiang** [comment]
take 1hr

**Comment by royal0721** [comment]
> take 2hr（1hr debug，1hr fix） 已修正一版，待重測 @royal0721

早上測試 ok ,  待下午重新測試
