### ISSUE TITLE
setup tidebixex for staging

### ISSUE THREAD

**Issue by jackal998** [CAFECA-IO/TideBitEx#335]
建置TideBitEX 到Docker staging上 （須先完成lagacy)

**Comment by jackal998** [comment]
- (node:1366) [SEQUELIZE0006] DeprecationWarning: This database engine version is not supported, please update your database server

- DB    tidebitstaging connect success
Trace: TypeError: Cannot read property 'app' of undefined
    at /root/worksapce/TideBitEx/backend/bots/ExchangeHub.js:37:35
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by jackal998** [comment]
setup ok
但是routing有些意料之外的事情
待aws 部署完畢後交互檢查

2 hr

**Comment by jackal998** [comment]
docker ok

total 6 hr (2+4) done

紀錄：
image base on ubuntu:14:04, last commit(image) was tidebit:v2

start container command:
docker run -it --name tidebit_v2 -v tidebit:/root -p 80:80 -p 443:443 -p 3000:3000 -p 3306:3306 -p 4567:4567 -p 6379:6379 -p 8080-8082:8080-8082 -p 18080:18080 tidebit:v2 bash

待[#128](https://github.com/CAFECA-IO/TideBit-Lagacy/issues/128)更新部署文件。

**Comment by Luphia** [comment]
- to be test

**Comment by jackal998** [comment]
member ok ( id = 60996)
trading function ok

但是目前卡在訂單送出/成交 畫面需重新整理才會顯示，應該是daemon的問題

另開為 [#361](https://github.com/CAFECA-IO/TideBitEx/issues/361)
