### ISSUE TITLE
Integrate ExchangeRate Module：

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#35]
- 創建 class Trader
    - 負責獲取 Exchange rate 更新 Exchange rate 
- 整合 API
- 將 Data 整合到 UI 上

**Comment by TzuHanLiang** [comment]
似乎沒有這個需求

**Comment by TzuHanLiang** [comment]
- 解法修改為
  - 目前由 `https://cc.isun.one/api/cc/PriceList` 取得匯率
  - 將匯率與 getAccounts 這隻 api 一起回傳給前端
- 目前沒有或是沒有找到介面上修改法定貨幣的位置，目前法定貨幣為 港幣

**Comment by TzuHanLiang** [comment]
> * 解法修改為
>   
>   * 目前由 `https://cc.isun.one/api/cc/PriceList` 取得匯率
>   * 將匯率與 getAccounts 這隻 api 一起回傳給前端
> * 目前沒有或是沒有找到介面上修改法定貨幣的位置，目前法定貨幣為 港幣

更新成同 TideBit-Lagacy 做法 #799
- 法定貨幣為 hkd
- 其餘法幣金額使用下列匯率與 hkd 轉換
```
    hkd: 1,
    twd: 0.2623,
    jpy: 0.0715,
    krw: 0.0073,
    usd: 7.8,
    eur: 8.9341,
    try: 1.4637,
```
- 虛擬貨幣則使用 ticker: [currency]/HKD 的實時價格
- 若上述  ticker 不存在就找到這個貨幣是否在我們支援的其他交易對裡面，在的話就用這個交易對的價格 * quoteUnit 的價格，若不在即為 0

**Comment by Julian0701** [comment]
使用[TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000006_%E4%BA%A4%E6%98%93%E7%95%8C%E9%9D%A2%E7%9A%84%E5%8D%B3%E6%99%82%E6%9B%B4%E6%96%B0%E6%AA%A2%E9%A9%97.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000006 交易界面的即時更新](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000006/20221104.md
)驗證通過
