### ISSUE TITLE
[BUG] OKEx postOrder error with insufficient balance

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#358]
1. 用 analysis 看 Balance 夠，但是在 postOrder的時候卻會出現 postOrder error with insufficient balance， 
2. 目前 balance 均由改寫DB得到的，所以與實際的可用餘額是不一致的，也可能會導致postOrder error with insufficient balance

**Comment by royal0721** [comment]
20220609 發現限價單買進賣出失敗 [#230](https://github.com/CAFECA-IO/TideBit-Lagacy/issues/230)

**Comment by Luphia** [comment]
- 設定無異常

**Comment by TzuHanLiang** [comment]
- 測試額度限制： 並無額外限制
- 之所以會出現 subAccount 金額超過交易金額卻顯示餘額不足的原因是，我們現在使用的是主帳號來作為交易帳戶（金額比對到錯誤的地方）
- Analysis 頁面要有可以顯示主帳號各幣種可交易的金額 @Luphia

**Comment by Luphia** [comment]
- no need to fix
