### ISSUE TITLE
[bugs] daemons 不穩定，待確定原因

### ISSUE THREAD

**Issue by jackal998** [CAFECA-IO/TideBitEx#361]
case 1
訂單簿交易量已改變，但即使重新整理之後最新成交依舊無更新

case 2
交易送出後畫面僅有flash出現，其餘皆無改變，但重新整理之後掛單簿有變化，最新成交也有變化

**Comment by jackal998** [comment]
case 1 solved [#357](https://github.com/CAFECA-IO/TideBitEx/issues/357)

**Comment by Luphia** [comment]
- Job Cancel
