### ISSUE TITLE
[bug] mailer can't send email

### ISSUE THREAD

**Issue by jackal998** [CAFECA-IO/TideBitEx#365]
case 1 
no activation mail was sent

**Comment by jackal998** [comment]
check rabbitMQ setting similar to peatio.orderbook.slave

Exchange: peatio.notification
Queue peatio.notification.email

Exchange: peatio.orderbook
Queue peatio.orderbook.slave

and orderbooks works good

*需要啟動daemon:notification_email
bundle exec rake daemon:notification_email:start

4 hr used

**Comment by jackal998** [comment]
check
  - AMQP config normal
  - AMQP enqueue normal
  - rabbitmq flow normal
  - daemon:notification_email normal (queue.subscribe then work.process)

modify
  - application.yml
```
from

SMTP_PORT:            587
SMTP_DOMAIN:          'gmail.com'
SMTP_ADDRESS:         'smtp.gmail.com'
SMTP_USERNAME:        'baron.chow@isuntv-hk.com'
SMTP_PASSWORD:        '!qaz@wsx'
SMTP_AUTHENTICATION:  'login'

to

SMTP_PORT:            587
SMTP_DOMAIN:          'gmail.com'
SMTP_ADDRESS:         'smtp.gmail.com'
SMTP_USERNAME:        'developer@mermer.cc'
SMTP_PASSWORD:        'hnjrioayllgrgsan'
SMTP_AUTHENTICATION:  'plain'
```

mailer works on docker but not aws

pending check list:
  - cloudflare settings
  - rabbitmq setting
  - smtp setting

5 hr used, total 9 hr used, 3 hr togo

**Comment by jackal998** [comment]
aws test ok with rabbitmq restart!

1 hr used, total 10 hr used done

**Comment by royal0721** [comment]
20220517 測試 ok
