### ISSUE TITLE
[BUG][UI][MOBILE] DepthChart

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#384]
- [問題] 
  - x & y axis take more area than chart
  - 不同價格區間的座標不一樣
- [解決方案]
  - 取消 library 的橫縱座標，自己畫
<img width="427" alt="Screen Shot 2022-05-17 at 4 24 56 PM" src="https://user-images.githubusercontent.com/17249354/168765652-eca53311-5582-4fe8-98c7-d5d9694c02df.png">

**Comment by Luphia** [comment]
execution time

**Comment by Luphia** [comment]
used 2 hrs
