### ISSUE TITLE
TideBit 前端 Sequence diagram

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#392]
1. TideBit 前端 Sequence Diagram 繪製 - start, trading 
2. 尋找合適的 UML 工具和 sample
4. 確認繪製時出現的問題並解決

**Comment by TzuHanLiang** [comment]
流程修改 App Start：

1. fetch data: middle call communitcator to fetch data, 拿到資料後由 middleman call library‘s book update difference and snapshot
2. sync ： is storeProvider function， storeProvider call middleman get snapshot from library‘s book

**Comment by royal0721** [comment]
#424
