### ISSUE TITLE
[Function][UnitTest][TideBitConnector] _updateBooks

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#401]
負責更新從TideBit slanger 收到的最新 depthBook 資料， 更新的方式為 ```每次推送最新的數據```
資料格式為：
```
    {
        asks: [
            ['160.0', '2.0998'],
            ['300.0', '1.0']
        ], 
        bids: [
            ['110.0', '13.4916'],
            ['10.0', '0.118']
        ]
    }
}
```
- 收到資料後分別將 asks，及 bids 以下述的方式整理， amount 為0 的判斷為需要移除的資料，其餘均認為是新增。
- 將整理後的資料使用 DepthBook library 裡面的 ```updateByDifference``` 將資料更新， ```updateByDifference```在處理 add 時會先將 DepthBook物件裡面紀錄相同 market 裡面相同price的資料移除，需要檢查這樣的更新方法是否正確。

**Comment by Luphia** [comment]
execution time

**Comment by Luphia** [comment]
used 8 hrs
