### ISSUE TITLE
[UnitTest][Frontend] _getBooks

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#402]
- API fetch latest Book
- use DepthBook updateAll 記錄在 DepthBook 物件裡
  - 使用 ```_formateBook``` 將資料轉為 DepthBook可以使用的格式
```
[
    {
        id: '123.0',
        price: '123.0',
        amount: '1',
        side: 'asks'
    },
    ...
]
```
  - 驗證 ```_calculateDifference``` 
  - 驗證 ```_trim```

**Comment by Luphia** [comment]
Fix in #401
