### ISSUE TITLE
[UnitTest][Frontend] getBooks

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#403]
- get DepthBook snapshot
  - 將latest 的 snapshot 與 latest 的 difference 做比較，只要同時存在difference 及 snapshot 的 order單， 即可認為這是新增的 order單 可以加上動畫， verify ```_compareFunction``` 。
  - 將 DepthBook snapshot 整理成頁面要用的格式。

**Comment by Luphia** [comment]
Fix in #404
