### ISSUE TITLE
[Function][UnitTest][OKExConnector] _updateTrades

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#412]
負責更新從OKEx收到的最新 trades 資料， 把所有收到的資料都當作新增的資料，使用 OKExConnector```_formateTrades```，轉換成 TradeBook 裡面使用的格式，要驗證 TradeBook的```updateByDifference```
-  TradeBook```updateByDifference```，在 concat ```{ add: [...trades]}```之前會先filter掉TradeBook snapshot 裡面與add裡面相同 id 的trade object
- 透過 TradeBook```getSnapshot``` 將最新資料傳給前端

**Comment by Luphia** [comment]
used 1 hr
