### ISSUE TITLE
[Function][UnitTest][TideBitConnector] _updateTrades

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#413]
負責更新從TideBit收到的最新 trades 資料， 把所有收到的資料都當作新增的資料，要驗證 TradeBook的```updateByDifference```
-  TradeBook```updateByDifference```，在 concat ```{ add: [...trades]}```之前會先filter掉TradeBook snapshot 裡面與add裡面相同 id 的trade object
- 透過 TradeBook```getSnapshot``` 將最新資料傳給前端，要驗證傳送的資料格式是否符合需求

**Comment by TzuHanLiang** [comment]
take 1hrs

**Comment by Luphia** [comment]
no pull request
