### ISSUE TITLE
[Function][UnitTest][TideBitConnector] _updateTrade

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#414]
負責更新從TideBit收到的最新的 private trade 資料，使用 TradeBook的```updateByDifference```
-  TradeBook```updateByDifference```，在 concat ```{ add: [...trades]}```之前會先filter掉TradeBook snapshot 裡面與add裡面相同 id 的trade object
- 透過 TradeBook```getDifference``` 將最新資料傳給前端，要驗證傳送的資料格式是否符合需求

**Comment by TzuHanLiang** [comment]
take 1hrs

**Comment by Luphia** [comment]
no pull request
