### ISSUE TITLE
[Web Assets]通過金管會 Banner

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/TideBitEx#418]
TideBit 在台通過金管會消息Banner

**Comment by JodieWu** [comment]
完成時間：2.5 hr
https://drive.google.com/drive/folders/1-pWa9R1MdpXK_OAJ13JPQLHPCrV8Dh9H?usp=sharing

**Comment by JodieWu** [comment]
修改時間：1 hr
https://drive.google.com/drive/folders/1-pWa9R1MdpXK_OAJ13JPQLHPCrV8Dh9H?usp=sharing

**Comment by Luphia** [comment]
- 需制定 Banner 設計風格規範
