### ISSUE TITLE
[Web Assets]  支援在台銀行 Banner

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/TideBitEx#419]
TideBit 支援在台銀行-第Ｎ個合規經營的交易所

**Comment by JodieWu** [comment]
完成時間：2.5 hr
https://drive.google.com/drive/folders/1-pWa9R1MdpXK_OAJ13JPQLHPCrV8Dh9H?usp=sharing

**Comment by Luphia** [comment]
- 需制定 Banner 設計規範
