### ISSUE TITLE
將 TideBitEx 整合到 TideBit staging

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#42]
- 將 #55  TideBitEx 移植到 TideBit-Legacy的可行性評估 的實驗結果 移植到 TideBit-Legacy上
- 資料串接

**Comment by TzuHanLiang** [comment]
strategy:

- update TideBitEx UI with old react and old library
   "node-sass": "^3.13.0",
    "react": "^0.14.7",
    "react-dom": "^0.14.7",
    "react-redux": "^4.4.0",
    "redux": "^3.3.1",

- switch TideBit-Legacy react component with TideBitEx

**Comment by TzuHanLiang** [comment]
- take 3hrs to build TideBit-Legacy project [failed]
- take 1hrs to switch update TideBitEx UI with old react and old library

expect to take another 5hrs to finish

**Comment by Luphia** [comment]
split to #85 #55
