### ISSUE TITLE
[UnitTest][Frontend][messageHandler] update trade

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#420]
TODO： 確保有監聽此事件
Events.trade 
- 確認 Backend 每次推過來的是 difference
- 收到資料後使用 updateByDifference 更新 TradeBook 裡面的資料， 要驗證是否正確。
- trim data 到合適的長度

**Comment by TzuHanLiang** [comment]
現在動畫不符合預期

**Comment by TzuHanLiang** [comment]
現在動畫不符合預期

**Comment by TzuHanLiang** [comment]
資料已確認，動畫還是不對

**Comment by Luphia** [comment]
turn off animation
