### ISSUE TITLE
OrderBook 優化： 提供 range 功能

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#48]
可以設定books price 區間
<img width="323" alt="Screen Shot 2022-02-14 at 12 10 55 PM" src="https://user-images.githubusercontent.com/17249354/153798751-3896e5e8-692c-4aba-b023-b20040d912e8.png">

**Comment by TzuHanLiang** [comment]
take 5hrs, remain 2hrs

**Comment by Luphia** [comment]
Fix #507 first

**Comment by Luphia** [comment]
- pull request information
