### ISSUE TITLE
[後台管理] 交易管理 - 支援幣種設定

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#492]
- 支援幣種的設定有四種子開關：充值、提現、劃轉（有多個子帳戶時啟動）、交易（不存在活躍交易市場時關閉）。如果四種狀態都是關閉，則該幣種從系統下架不再顯示。新增支援幣種管理頁面，介面上可以開啟或關閉支援幣種
- 確認當管理者開啟或關閉幣種，使用者的充值、提現、劃轉、交易頁面上的幣種會隨之顯示或不顯示

![Image](https://user-images.githubusercontent.com/17249354/172541656-13f03fac-3455-4f53-a3b9-e1a5df4fe07f.png)

**Comment by TzuHanLiang** [comment]
設計改版 + 功能實作 預計還需3hrs

**Comment by TzuHanLiang** [comment]
take 3hrs

**Comment by TzuHanLiang** [comment]
switch 要加防呆設計， openall， closeall 也要防呆 ，remain 1hr

**Comment by TzuHanLiang** [comment]
take 1hr to finish

**Comment by Luphia** [comment]
- pull request information
