### ISSUE TITLE
[後台管理][UI 待確認] 權限管理

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#497]
- UI 需求
  - ~需要一個頁面或是 dialog 對沒有admin權限的 user 顯示不可訪問，請申請升級權限之類的~
  - 需要一個 users 列表，可以新增跟刪除 user，並且只有特定角色（：root）有可以修改不同 user 的角色
  - user資訊包含：
    - id
    - email
    - roles（root、accountant、operating、worker、supervisor、withdraw checker、deposit checker、deposit maker、KYC checker、deposit viewer）角色可以複選

- 功能需求
  - 用戶帳號管理
    - 新增權限管理介面，確保 super user 會在建立 admin user 後被鎖上，接著系統管理會由 admin user 進行管理
    - 可以新增或刪除角色，並為用戶新增角色或替換角色
    - ~確認可以針對用戶改密碼、設定密碼過期日、強制用戶更新密碼~

**Comment by TzuHanLiang** [comment]
- take 5hrs
  -  實作部份ui 及功能
- remain 3hrs 
  - ui 微調
  - 功能 微調

**Comment by TzuHanLiang** [comment]
take 3hrs

**Comment by Julian0701** [comment]
使用[TBETC000002](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000002_%E7%AE%A1%E7%90%86%E6%AC%8A%E9%99%90%E5%B8%B3%E8%99%9F.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000002 管理權限帳號功能](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000002)驗證通過
