### ISSUE TITLE
[BUG] DepthBook range for asks side order 無條件進位

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#507]
src/libs/books/DepthBook.js: ln38 
`for (let i = 0; i < arr.length; i++) {
        const p = arr[i];
        let price = parseInt(parseFloat(p.price) / unit) * unit;
        // if (p.side === "asks" && parseFloat(p.price) % unit > 0) price += unit; // ++ TODO make sure this function working properly
        if (result[price]) {
          if (SafeMath.eq(result[price].amount, "0")) {
            result[price] = { ...p, price };
          } else {
            result[price].amount =
              parseFloat(result[price].amount) + parseFloat(p.amount);
          }
        }
      }`

**Comment by Luphia** [comment]
- execution time
- pull request information

**Comment by TzuHanLiang** [comment]
take 1hrs
