### ISSUE TITLE
[BUG] 限價單賣出 Trade 更新不完全

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#545]
## 使用功能：
TideBit Trading
## 狀況重現步驟：
1.  使用者帳號登入
2.  進入 https://legacy2.tidebit.network/markets/ethhkd
3.  在限價單第一欄位輸入目前Ask最高價
4.  第二欄位輸入0.1
5.  按下 Sell
6.  再重複步驟3-5
8. 交易皆有完成，但是Trade 只有出現一次交易紀錄

## 實際狀況
![](https://i.imgur.com/k8hBukt.png)

**Comment by royal0721** [comment]
20220617 今日測試發現Trade顏色有誤 無法將 Close Order 與 Trade 同步
![](https://i.imgur.com/6Dasqrl.png)

**Comment by TzuHanLiang** [comment]
take 1hr
