### ISSUE TITLE
[BUG] 市場沒有 Ask 掛單時 , Bid 未對齊中線

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#546]
## 使用功能：
TideBit Trading
## 狀況重現步驟：
1.  使用者帳號登入
2.  進入 https://legacy2.tidebit.network/markets/ethhkd
3.  將市場上的 Ask 掛單全數買進
4.  出現 DepthBook Bid 掛單沒有對齊中線的問題

## 實際狀況

![](https://i.imgur.com/AHm41RD.png)

**Comment by TzuHanLiang** [comment]
also fixed DepthBook range function(  javascript 數學除不盡的問題）take3hrs

**Comment by royal0721** [comment]
20220705 下午測試 ok
