### ISSUE TITLE
[BUG]OKEx無法使用Available資產進行限價買進

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#547]
## 使用功能：
OKEx Trading
## 狀況重現步驟：
1.  已有USDT的帳號登入
3.  進入 OKEx Trading 頁面
4.  在 limit 的第一欄位輸入 0.01
5.  第二欄位輸入1  
6. 顯示Error message 
## 期待結果
正常掛單
## 實際狀況
![](https://i.imgur.com/rDhCsGT.jpg)

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by royal0721** [comment]
20220705 下午測試 ok
