### ISSUE TITLE
[BUG] 掛單交易更新的 Status 大小寫沒有統一

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#548]
## 使用功能：
TideBit Trading
## 狀況重現步驟：
1.  使用者帳號登入
2.  進入 https://legacy2.tidebit.network/markets/ethhkd
3.  限價單第一欄位輸入Bid最大值
4.  第二欄位輸入Bid最大值的一部分Volume
5.  按下Sell
6.  重複步驟3-5一次
7.  Trade只更新一次，並未更新兩次
## 實際狀況
![](https://i.imgur.com/yALjeUa.png)

**Comment by TzuHanLiang** [comment]
take 1hr
