### ISSUE TITLE
[BUG] 限價單買進市場一筆交易單時 Trade 和 My Order 顯示不同

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#549]
## 使用功能：
TideBit Trading
## 狀況重現步驟：
1.  使用者帳號登入
2.  進入 https://legacy2.tidebit.network/markets/ethhkd
3.  將市場上的 Ask 掛單全數買進
4.  出現 Trade Amount 和 My Orders 顯示不同步的問題
## 實際狀況
Trade最上方的兩筆交易Amount相加不為1
![](https://i.imgur.com/AHm41RD.png)

推測可能：
在進行交易時，推測 Depth Book 並未顯示全部市場的交易單，因此在沒有看到 Ask 有掛單的情況下仍然完成交易，但顯示的金額仍無法與完成的 Order 同步

**Comment by Luphia** [comment]
cannot be reproduced
