### ISSUE TITLE
[後台管理 UI] 入金管理更新

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#553]
- old design

![Image](https://user-images.githubusercontent.com/17249354/174511804-afb8af37-b171-42dc-a70d-632357b85964.png)

- new design

<img width="1233" alt="Screen Shot 2022-06-23 at 3 36 14 PM" src="https://user-images.githubusercontent.com/17249354/175243602-ed1ac234-8fac-48c9-96d7-e5b32242d66e.png">

**Comment by TzuHanLiang** [comment]
take 2hrs

**Comment by Luphia** [comment]
- pull request information
