### ISSUE TITLE
[UX] Wireframe 管理介面優化

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/TideBitEx#554]
整合頁面，減少操作步驟

**Comment by JodieWu** [comment]
完成時間：2.5 hr

**Comment by Luphia** [comment]
- 補上調整說明
- 成果連結

**Comment by JodieWu** [comment]
整合手續費調整及入金管理與交易對管理頁面
https://xd.adobe.com/view/a0164253-ea4b-442b-b8f2-469d79b68e28-f545/
