### ISSUE TITLE
[BUG] 切換交易對 資產限制警示未更新

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#569]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://legacy2.tidebit.network/markets/usdthkd)
3.  於限價賣出的第二欄位輸入0.01
4.  點擊交易對名稱開啟切換交易對視窗
5.  點擊 ETH/HKD
6.  Minimum amount 未更新 （要再次輸入值才會更新）

## 期待結果
自動更新Available amount 或者不顯示
## 實際狀況
![](https://i.imgur.com/hXxEXmn.png)

**Comment by TzuHanLiang** [comment]
take 3hrs

**Comment by royal0721** [comment]
20220628 下午測試通過
