### ISSUE TITLE
[BUG]交易對Bid&Ask數值顯示異常

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#570]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://legacy2.tidebit.network/markets/ethhkd)
3.  於限價買進第二欄位輸入小於市場價格的數值
4.  第二欄位輸入1
5.  點擊賣出
6.  掛單成功但數值為改變
7.  刷新後更新Bid數值（該價格的Volume+1)而非在DepthBook增加一筆該金額的掛單
## 期待結果
DepthBook更新正確
## 實際狀況
![](https://i.imgur.com/ICglfG6.png)

**Comment by royal0721** [comment]
20220624 DepthBook 刷新後沒有改變
![](https://i.imgur.com/uVFocRG.png)

**Comment by TzuHanLiang** [comment]
- take 3hrs

線索：
- SlaveBook process 可能負責更新 depthBook

**Comment by TzuHanLiang** [comment]
fixed by #655

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by royal0721** [comment]
實際結果：
Bid&Ask數值顯示正常
![](https://i.imgur.com/Bqg9Z3h.png)
