### ISSUE TITLE
[BUG]DepthBook未自動刷新

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#571]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://legacy2.tidebit.network/markets/ethhkd)
3.  於限價買進第二欄位輸入小於市場價格的數值
4.  第二欄位輸入1
5.  點擊賣出
6.  掛單成功但數值未改變
8.  刷新後更新

## 期待結果
DepthBook更新正確

## 實際狀況
![](https://i.imgur.com/P0OKPnN.png)

**Comment by royal0721** [comment]
影響範圍 市價單交易 限價單交易 取消交易

**Comment by royal0721** [comment]
20220624
DepthBook 不會自動刷新 刷新後數值沒有改變
![](https://i.imgur.com/uVFocRG.png)

**Comment by TzuHanLiang** [comment]
- OrderBookManager
  - app/models/matching/order_book_manager.rb
- SlaveBook
- OrderCreation
- Executor
- Engine
- OrderCreation

**Comment by royal0721** [comment]
20220707 下午測試狀況重現

**Comment by TzuHanLiang** [comment]
fixed by #655 without PR

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by royal0721** [comment]
實際測試結果：
Depthbook 自動刷新
![](https://i.imgur.com/YayweFN.png)
