### ISSUE TITLE
[BUG]MyOrders未自動刷新

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#572]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://legacy2.tidebit.network/markets/ethhkd)
3.  於限價買進第二欄位輸入小於市場價格的數值
4.  第二欄位輸入1
5.  點擊賣出
6.  掛單成功但數值未改變
8.  刷新後更新

## 期待結果
ＭyOrders更新正確

## 實際狀況
![](https://i.imgur.com/P0OKPnN.png)

**Comment by royal0721** [comment]
影響範圍 市價單交易 限價單交易 取消交易

**Comment by royal0721** [comment]
20220624 下午測試 已修復

**Comment by TzuHanLiang** [comment]
take 1hr 測試，有時有更新，大部分沒有

**Comment by royal0721** [comment]
20220705 下午測試發現問題重現
TideBit, OKEx 皆不會自動刷新
![](https://i.imgur.com/X3VppJd.jpg)
![](https://i.imgur.com/5m3UaaS.jpg)

**Comment by royal0721** [comment]
20220707 下午測試發現問題重現
TideBit, OKEx 皆不會自動刷新
限價單：沒有撮合的掛單刷新後會出現 但不會出現完整的掛單
市價單：無法進行市價單交易 故無法測試
取消掛單：刷新後不會改變

**Comment by TzuHanLiang** [comment]
duplicate #731

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by royal0721** [comment]
實際測試結果：
MyOrders 自動刷新
![](https://i.imgur.com/uWQDmjC.png)
