### ISSUE TITLE
[BUG]交易無法撮合成功

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#573]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://legacy2.tidebit.network/markets/ethhkd)
3.  於限價買進第二欄位輸入小於市場價格的數值
4.  第二欄位輸入1
5.  點擊賣出
6.  掛單成功但數值未改變
8.  刷新後更新
9.  市場上有人掛單子 照理來說應該正常撮合 但是一直卡在 Close Orders

影響範圍： 市價單交易 限價單交易 取消交易
## 期待結果
搓合成功

## 實際狀況
![](https://i.imgur.com/P0OKPnN.png)

**Comment by TzuHanLiang** [comment]
duplicate #585

**Comment by Luphia** [comment]
fix with #692

**Comment by royal0721** [comment]
20220830 測試結果->未重現
![](https://i.imgur.com/klGsh2P.png)
![](https://i.imgur.com/qBhYweA.png)
