### ISSUE TITLE
[BUG] OKEx 手續費異常

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#584]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://legacy2.tidebit.network/markets/ethusdt)
3.  於限價買進第二欄位輸入大於市場價格的數值
5.  第二欄位輸入1
6.  點擊買入
7.  掛單成功後查看History
8.  手續費異常

影響範圍： 市價單交易 限價單交易 取消交易
## 期待結果
手續費正常

## 實際狀況
![](https://i.imgur.com/6Y4Qzxh.png)

**Comment by TzuHanLiang** [comment]
> 20220705 下午測試重現

若有重現，請幫忙附上對應的圖片，謝謝

**Comment by TzuHanLiang** [comment]
take 1hr

**Comment by Luphia** [comment]
需要具體重現流程與該測試案例

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by TzuHanLiang** [comment]
- ETH/USDT， 手續費收 0.003

![Image](https://user-images.githubusercontent.com/17249354/184851596-fbef4536-2970-41bd-8e00-a9ad66536ade.png)

- 測試結果截圖
![Image](https://user-images.githubusercontent.com/17249354/184851298-90ba950f-2156-494e-8265-3c846ae8496a.png)
