### ISSUE TITLE
[BUG] eth/usdt 無法正常撮合成功

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#585]
## 使用功能：
OKEx Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://legacy2.tidebit.network/markets/ethusdt)
3.  於限價買進第二欄位輸入大於市場價格的數值
5.  第二欄位輸入1
6.  點擊買入
7.  掛單成功後但無法完成撮合

影響範圍： 市價單交易 限價單交易 取消交易
## 期待結果
完成撮合

## 實際狀況
![](https://i.imgur.com/UxkUbAt.jpg)

**Comment by TzuHanLiang** [comment]
- take 5hrs

module Matching
  class Executor 負責撮合

**Comment by Luphia** [comment]
fix with #692

**Comment by royal0721** [comment]
20220830 測試結果 有撮合成功
![](https://i.imgur.com/tm0IyQj.jpg)
![](https://i.imgur.com/LzAS3cj.jpg)
