### ISSUE TITLE
[BUG]Orderbook 雙邊長度需要對齊

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#587]
## 使用功能：
OKEx Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面-btcusdt](https://legacy2.tidebit.network/markets/btcusdt) 
3.  查看 OrderBook 
4.  雙邊沒有對齊

## 期待結果
雙邊長度對齊

## 實際狀況
![](https://i.imgur.com/fZupPJk.png)

**Comment by TzuHanLiang** [comment]
take 3hrs

**Comment by royal0721** [comment]
20220628 下午測試通過
