### ISSUE TITLE
[BUG] Setting 頁面不能垂直滑動

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#650]
## 使用功能：
帳戶設置頁面
## 狀況重現步驟：
1.  使用已驗證的帳號登入
2.  進入帳戶設置頁面
3.  無法垂直滑動 overflow 缺乏 scrollbar

## 期待結果
可以自由上下滑動

## 實際狀況
![](https://i.imgur.com/Q59bGU2.png)

**Comment by royal0721** [comment]
20220802 測試重現 包括 KYC 頁面也有相同問題

**Comment by TzuHanLiang** [comment]
take 1hr 修復，side effect： sidebar 打不開， 預計 remain 2hr

**Comment by TzuHanLiang** [comment]
fixed take 2hrs #735

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by TzuHanLiang** [comment]
https://user-images.githubusercontent.com/17249354/184851998-a631c0be-a90f-4096-977e-2a5d18b171b1.mov
