### ISSUE TITLE
[BUG] okex-ticker ws 沒有監聽到的 close order 會沒有記錄到DB

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#658]
## 問題
- 目前 My Orders/ Close orders 裡面的 orders 是指從 DB 拿，沒有問 API
- close orders 更新的方法是 ws 監聽到後才會更新，所有當server crash時 order 更新就會沒有記錄到

## 解法
- 在 OkexConnector 裡面寫一個 sync function，10分鐘 sync 一次
- sync 裡面會取所有 okex 的 trades history
- emit Event.tradesDetailUpdate 到 ExchangeHub
- 由 _updateTradesDetail 更新 trades 
  - => 避免重複記錄的方法: 
    - 在 trades table 裡面 新增一個 trade_fk 用來辨別記錄過的 okex  tradeId
    - 取到的 trades 到 DB 跟用 select not exist 過濾 
    - 呼叫 _updateTradeDetail 更新個別 trade 裡面關聯到的資料
 - _updateTradeDetail
```
    // 1. get order by trade.clOrdId from table
    // 2. _updateTrade => insert to DB
    // 3. _updateOrderbyTrade => insert to DB
    // 4. side === 'buy' ? _updateAccByBidTrade : _updateAccByAskTrade => insert to DB
    // 5. _updateVouchers => insert to DB
    // 6. add account_version => insert to DB

```

**Comment by TzuHanLiang** [comment]
take 3hrs
- //--HighRisk Behavior--// 制定計畫並確認可行性
- 確認要點：
  - 同時為 taker 及 maker 時，trades 會不會分開記錄 => 會，證據如下


![Image](https://user-images.githubusercontent.com/17249354/179205219-a989ce69-0436-4b3b-85ce-fe722209e155.png)

**Comment by TzuHanLiang** [comment]
## 計畫更新：
- [Checked] 新增一個 service（ExchangeHubService） class 
- [Checked] 在 TidebitEx 啟動後呼叫 service.start()
- [Checked] service.start call service.sync()
  - [Checked] 定期（10mins）執行工作
  - [Checked] 從 API 那 outerTrades 並寫入 DB
      - [unChecked] [Connector] fetchOuterTrades
      - [unChecked] [DBOperator] insertOuterTrades
  -[Checked] 觸發 _processOuterTrades()從 DB 取 outertradesrecord 更新下列 DB table trades、orders、accounts、accounts_version、vouchers
      - [unChecked] get all records from outer_trades table
      - [unChecked] fillter records if record.status === 5
      - [unChecked] _processOuterTrade
          - get order by trade.clOrdId from orders table
          - check if order.memberId === memberId, if not do nothing
          -  _updateOrderbyTrade
          - side === 'buy' ? _updateAccByBidTrade : _updateAccByAskTrade
          -  _updateTrade
          - _updateVouchers
          -  add account_version

**Comment by TzuHanLiang** [comment]
![Image](https://user-images.githubusercontent.com/17249354/180158687-718e1000-10cd-4a0b-a4df-ab4ab2414055.png)
[OKEx ticker 撮合流程 2022-07-21.txt](https://github.com/CAFECA-IO/TideBitEx/files/9157297/OKEx.ticker.2022-07-21.txt)

**Comment by TzuHanLiang** [comment]
由 #664 #665 #666 #667 #668 #669 #670 #671 #672 #676 完成

**Comment by Luphia** [comment]
#667 尚未完成

**Comment by TzuHanLiang** [comment]
#667 完成

**Comment by TzuHanLiang** [comment]
#667 完成
