### ISSUE TITLE
[BUG] [TransactionDetail 監聽] [process outerTrades] 更新原本的 Order

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#667]
關聯 #658

- 從 DB 取得關聯的 order 更新
  - 判斷 order 是否存在 及 order.state 及 memberId 是否符合更新條件
  - 是，根據 outerTrade 更新該 order
  - 否，若 order.memberId ！== memberId 說明該 order 是不在這個環境的， 會被剛剛取得的 order 設為 null
  - return updateOrder， 原來的 order

在 #668 部份會用 order 是否存在來判斷是否需要更新

**如果資料不夠的需即時討論** 取得額外資料的流程不在這裡處理

**Comment by TzuHanLiang** [comment]
take 2hrs

**Comment by TzuHanLiang** [comment]
- 經檢驗後得知，不是直接為0，而是透過 REASON.ORDER_FULLFILLED release locked balance
- take 1hr 驗證，1hr 更新code
<img width="1679" alt="Screen Shot 2022-08-10 at 2 16 37 PM" src="https://user-images.githubusercontent.com/17249354/183835998-823025e4-7268-43dc-827f-c0d0587e8020.png">

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by TzuHanLiang** [comment]
發現錯誤，需修正，updateAccount 沒有 620，且不應該是610而是600


![Image](https://user-images.githubusercontent.com/17249354/184848558-4c4ed833-ca7d-493e-856e-a54c646a7482.png)

**Comment by TzuHanLiang** [comment]
<img width="1679" alt="Screen Shot 2022-08-17 at 3 37 36 PM" src="https://user-images.githubusercontent.com/17249354/185062045-fa9b584b-086a-47b9-a1e2-c24ae2ba3161.png">

**Comment by TzuHanLiang** [comment]
<img width="1679" alt="Screen Shot 2022-08-17 at 5 14 45 PM" src="https://user-images.githubusercontent.com/17249354/185082013-1ccafb70-3c6a-4e31-a6cc-33d10f3c09b7.png">

**Comment by TzuHanLiang** [comment]
![Uploading Screen Shot 2022-08-17 at 6.25.54 PM.png…]()

**Comment by TzuHanLiang** [comment]
<img width="1679" alt="Screen Shot 2022-08-17 at 6 25 54 PM" src="https://user-images.githubusercontent.com/17249354/185101858-822704d3-9705-49d9-80a6-c72dcb02be0f.png">

**Comment by TzuHanLiang** [comment]
take 5hrs
