### ISSUE TITLE
[BUG] Tidebit 交易無法撮合

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#681]
## 使用功能：
Trading
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  於現價買入第一欄位輸入目前 Bid 的最小值
4.  第二欄位輸入小於 Available Amount 的數值
5.  按下買進
6.  顯示掛單成功，無法撮合成功

影響範圍：限價單, 市價單買進賣出

## 期待結果
限價單, 市價單買進賣出可以正常掛單並成功

## 實際狀況
![](https://i.imgur.com/KvYAl2J.png)

**Comment by royal0721** [comment]
20220802 測試重現

**Comment by royal0721** [comment]
20220808 測試重現 發現 btc/hkd 可以撮合 但 eth/hkd 無法撮合

**Comment by royal0721** [comment]
20220809 測試無重現 -> can't reproduce

**Comment by TzuHanLiang** [comment]
- take 2hrs
  - 經檢驗無法撮合的原因是  uncatch error 導致 server crush，沒有接到的錯誤時 okexConnector _updateTrade 傳進來的參數有錯誤，錯誤造成的原因是為了解決 issue #714( PR #715 ) 調整送到 _updateTrade 方法的參數，但是漏改到 _updateTrade 方法的接口，導致參數不匹配而出錯。

**Comment by TzuHanLiang** [comment]
duplicate with #733

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by royal0721** [comment]
實際結果如下：
Tidebit 可以撮合成功
https://drive.google.com/file/d/1ok9k31YT4AhH-dTNFRU6ERS9zDhEiMob/view?usp=sharing
