### ISSUE TITLE
Bank company 資料建檔

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#682]
建立 bank 資料

**Comment by royal0721** [comment]
花費時間 5 mins
建立銀行模擬資料

**Comment by royal0721** [comment]
dropdown() 出問題 -> 推測是 code ran before the jQuery library being fully loaded to the browsers
__webpack_require__(63); // failed
__webpack_require__(65); // failed
__webpack_require__(67); // failed
__webpack_require__(68); // failed

**Comment by Luphia** [comment]
- Job Cancel
