### ISSUE TITLE
[BUG] Tidebit , OKEx trading 卡在登入分頁

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#686]
## 使用功能：
Tidebit , OKEx Trading
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  卡在登入頁面無法進行交易

影響範圍：Tidebit, OKEx 限價單, 市價單買進賣出

## 期待結果
Tidebit, OKEx 限價單, 市價單買進賣出可以正常掛單並成功

## 實際狀況
![](https://i.imgur.com/XN0Fxvp.png)

**Comment by royal0721** [comment]
20220726 下午5:05測試第二次 無此情況產生

**Comment by royal0721** [comment]
20220727 下午5:02 測試重現

![](https://i.imgur.com/HFhScQM.png)

**Comment by royal0721** [comment]
20220728 重現
發現是新用戶註冊馬上進入到Trading會卡在登入分頁
若重新登入則無

**Comment by royal0721** [comment]
20220802 測試無法重現 -> can't reproduce

**Comment by royal0721** [comment]
20220809 測試重現
發現是新用戶註冊馬上進入到Trading會卡在登入分頁
若重新登入則無
![](https://i.imgur.com/qQ66fyW.png)

**Comment by TzuHanLiang** [comment]
- take 8hrs

**Comment by royal0721** [comment]
20220824 測試未重現
新註冊用戶不會出現此情況
![](https://i.imgur.com/Xhao7za.png)

**Comment by TzuHanLiang** [comment]
- take 1hr remain 1hr ， 將email 及memberId 寫在cookie 上，前端可以直接用，並在server端驗證與 session是否一致，不一致則刪除
