### ISSUE TITLE
[BUG] OrderBook Bid and ask 數值超出範圍

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#708]
## 使用功能：
Trading
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  於限價買入第一欄位輸入目前 Bid 的最小值
4.  Order Book Bid 數值最大值 > Ask 最小值

影響範圍：限價單, 市價單買進賣出

## 期待結果
限價單 Order 可以撮合成功並更新

## 實際狀況
![](https://i.imgur.com/eqz18oA.png)

**Comment by TzuHanLiang** [comment]
- 解法 about 2hrs remain
  - 調整 depthbook 初始的full snapshot，使用websocket 傳來的資料，不要使用api
    - okexConnector init 流程調整，在websocket init 時不要await，之後直接set okexListener
    - remove interval depth api request

**Comment by royal0721** [comment]
實際結果：
OrderBook Bid and ask 數值並無超出範圍
![](https://i.imgur.com/jD74ZvJ.png)
