### ISSUE TITLE
[BUG] Sell and Buy button overlay

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#717]
## 使用功能：
Trading

## User details:
Chrome PC Mac
1440x821

## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  Sell 和 Buy button 超出  border

## 期待結果
Sell 和 Buy button 不會超出 border

## 實際狀況
![](https://i.imgur.com/IRMyQjY.png)

**Comment by royal0721** [comment]
20220809 測試通過 已經修復

**Comment by TzuHanLiang** [comment]
take 1hrs

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by royal0721** [comment]
實際結果截圖：
Sell 和 Buy button 皆無與 border 重疊
![](https://i.imgur.com/JovwncF.png)
