### ISSUE TITLE
[BUG] TideBit tickers trades 的更新、depthbooks更新及圖表更新邏輯調整

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#722]
- #558 #716 #714 分別調整了 okex tickers的trades 的更新、depthbooks更新及圖表更新的邏輯。
- 由於當時在自己的測試環境測試，沒有 TideBit tickers 的資料，所以還未確認 TideBit tickers 是否需要做對應的調整
- 預計使用 new.tidebit.com 使用的 ws.tidebit.network 來確認及做對應的調整
- 三個部份需要調整
  -  trades 的更新 ，約 1.5hr
  -  depthbooks的更新，約 1.5hr
  -  圖表更新，約 2hr

**Comment by TzuHanLiang** [comment]
- take 2hrs， 圖表更新，約 2hr
- remain 3hr 
  - trades 的更新 ，約 1.5hr
  - depthbooks的更新，約 1.5hr

**Comment by TzuHanLiang** [comment]
take 4hr, 修正tidebit trades 更新錯誤

**Comment by royal0721** [comment]
20220815 測試未重現 -> 已經修復
