### ISSUE TITLE
[BUG] market頁面語言環境判斷邏輯調整

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#730]
第一次打開網站時，如果瀏覽器是中文配置，首頁（new.tidebit.com）會正常按瀏覽器語言“中文”顯示，但是打開交易界面（new.tidebit.com/markets/btchkd）時默認是 “English”，應該就是markets 頁面對於預設語言判斷機制與 tidebit.com 不一致造成，請保持和整體網站一樣的判斷邏輯。

**Comment by TzuHanLiang** [comment]
take 2hrs

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by TzuHanLiang** [comment]
將瀏覽器語言設定為中文
![Screen Shot 2022-08-16 at 5 45 27 PM](https://user-images.githubusercontent.com/17249354/184849985-7d6e5d88-2459-47d7-b476-34d552b3cd67.png)
打開test.tidebit.network為中文
![Screen Shot 2022-08-16 at 5 45 52 PM](https://user-images.githubusercontent.com/17249354/184849999-72744ed6-9ee2-45d2-a998-166effade06a.png)
打開交易界面為中文
![Screen Shot 2022-08-16 at 5 45 57 PM](https://user-images.githubusercontent.com/17249354/184850025-4237b269-5795-4990-9674-40cdc967ba17.png)

將瀏覽器語言設定為英文，打開test.tidebit.network為英文，打開交易界面為英文
https://user-images.githubusercontent.com/17249354/184850468-259c27b2-1409-49d1-98ad-82fa8274d436.mov

**Comment by Luphia** [comment]
Test Environment:
- windows 10
- chrome
- zh-HK

**Comment by royal0721** [comment]
20220829 待使用 windows 電腦測試

**Comment by Luphia** [comment]
- checked with surface pro
