### ISSUE TITLE
[BUG] DepthBook 未更新

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#731]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  於限價買進第二欄位輸入小於市場價格的數值
4.  第二欄位輸入1
5.  點擊賣出
6.  撮合成功但沒有更新 DepthBook

## 期待結果
DepthBook 更新正確

## 實際狀況
![](https://i.imgur.com/vOLtAAs.png)

**Comment by royal0721** [comment]
#722

**Comment by royal0721** [comment]
20220811 再次測試無此情況

**Comment by TzuHanLiang** [comment]
duplicate #571
