### ISSUE TITLE
[BUG] Trade 未自動更新

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#732]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  於限價買進第二欄位輸入小於市場價格的數值
4.  第二欄位輸入1
5.  點擊賣出
6.  撮合成功但沒有自動更新 Trade
7.  刷新後顯示

## 期待結果
Trade 自動更新
![](https://i.imgur.com/Ntz9l0l.png)

**Comment by royal0721** [comment]
20220811 測試未重現

**Comment by TzuHanLiang** [comment]
fixed by PR #754， details 參考 #681
