### ISSUE TITLE
[BUG] 市價單撮合成功 My Orders 未更新

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#733]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  於市價單買進的第二欄位輸入低於目前市價掛單的待交易數量
4.  點擊買進
6.  撮合成功但沒有更新 My Orders
7.  刷新後不會顯示

影響範圍： Tidebit Trading - 市價買進賣出
## 期待結果
My Orders 自動更新
![](https://i.imgur.com/Zqt0zt7.png)

**Comment by royal0721** [comment]
20220810 測試重現

**Comment by royal0721** [comment]
20220811 測試重現
![](https://i.imgur.com/8GMArUr.png)

**Comment by TzuHanLiang** [comment]
duplicate #572， fixed by #755

**Comment by Luphia** [comment]
合併至 #572 驗證
