### ISSUE TITLE
[BUG] 兩步驟驗證 QRCode 未顯示

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#738]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用未經過兩步驟驗證的帳號登入
2.  進入 Settings 頁面
3.  點擊 Google 兩步驟驗證
4. 未顯示 QRCode

## 期待結果
顯示 QRCode

![](https://i.imgur.com/f6laMjr.png)

**Comment by royal0721** [comment]
20220811 測試未重現 -> can't reproduce

**Comment by TzuHanLiang** [comment]
fixed by rebuild Tidebit-Legacy

**Comment by royal0721** [comment]
20220815 測試未重現 -> 已修復

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by royal0721** [comment]
實際結果截圖：
![](https://i.imgur.com/l3NuYl9.png)
