### ISSUE TITLE
OKEx 撮合成功未更新 MyOrder

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#739]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethusdt)
3.  於市價單買進的第二欄位輸入低於目前市價掛單的待交易數量
4.  點擊買進
6.  撮合成功但沒有更新 My Orders
7.  刷新後不會顯示

影響範圍： OKEx Trading - 市價買進賣出
## 期待結果
My Orders 自動更新
![](https://i.imgur.com/0CpdJP9.png)

**Comment by TzuHanLiang** [comment]
造成原因同 #744

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
合併至 #744 驗證
