### ISSUE TITLE
[BUG] 登入狀態不穩定

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#743]
- 還是容易突然丟失登錄狀態：多次反復刷新頁面後或者開著頁面一段時間不操作，在 markets 頁面突然丟失登錄狀態（但是如果打開 accounts 頁面顯示登錄狀態正常），必須重新“登錄”後才能繼續操作 markets 頁面。
與 #686 有關

- 解法：
- 使用 koa-session 把 memberId 及 peatio token 記錄在 server

**Comment by TzuHanLiang** [comment]
登入狀態丟失是因為在 redis 拿不到 buffer 或是 拿回的 buffer 長度與我們decode memberId 的長度不一致，且看起來並無包含membreId。
經確認 markets 頁面的 _peatio_session 始終與 tidebit 一致，所以不是 _peatio_session 過期導致的。
目前家裡 sync accounts及 sync myOrders 的機制所以如果出現， decode memberId 錯誤頁面會直接登出。

**Comment by TzuHanLiang** [comment]
解法：
在前端記錄 session

**Comment by royal0721** [comment]
20220818 測試重現
![](https://i.imgur.com/kOccXad.png)

**Comment by TzuHanLiang** [comment]
take 3hrs, 部份完成： 目前還沒有檢驗登出狀態的方法， remain 3hrs

**Comment by TzuHanLiang** [comment]
![Uploading Screen Shot 2022-08-19 at 09.36.57.png…]()

**Comment by TzuHanLiang** [comment]
<img width="1679" alt="Screen Shot 2022-08-19 at 15 54 53" src="https://user-images.githubusercontent.com/17249354/185575472-81b10d5a-429e-47aa-afae-96535f474de1.png">

**Comment by TzuHanLiang** [comment]
- take 5hrs

**Comment by royal0721** [comment]
20220819 測試無法重現

**Comment by TzuHanLiang** [comment]
PR 為 #770
