### ISSUE TITLE
[BUG] Tidebit 部分撮合成功 My Order 掛單消失

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#744]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  於限價單買進的第一欄位輸入低於目前市價的數值
4.  輸入低於目前最低 Ask 價的掛單 Amount 數量
5.  點擊買進
6.  掛單成功但在部分撮合成功幾秒後消失

影響範圍： Tidebit Trading - 限價買進賣出
## 期待結果
My Orders 更新
![](https://i.imgur.com/jyF4bBM.png)

**Comment by TzuHanLiang** [comment]
- fixed 2hrs
  - 錯誤是為了解 #753 調整了 orderBook 更新邏輯導致的，重新調整解法，這段已改回原本的版本

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by royal0721** [comment]
實際測試結果：
Tidebit 撮合成功 My Order 掛單消失
https://drive.google.com/file/d/1X1dqxn27CY3MsMXZPZ4lYpbtlnceUzAt/view?usp=sharing
