### ISSUE TITLE
[BUG] 價格精度問題：market 右側價格和 market list 精度不一致，在比較極端情況無法顯示數據

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#745]
整體交易界面-markets區域
價格精度問題：market 右側價格和 market list 精度不一致，在比較極端情況無法顯示數據
價格為0的時候也要顯示對應的精度

![Image](https://user-images.githubusercontent.com/17249354/184095139-62473dcb-51cc-4f49-8fb0-7c54c8d90e4c.png)

**Comment by TzuHanLiang** [comment]
take 3hrs
- 修正formateDecimal 的錯誤
  - 將 tickSz and lotSz 轉為精度
  - 將自然對數轉為 decimal

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by royal0721** [comment]
實際測試結果：
精度相同
![](https://i.imgur.com/C7EELKG.png)
