### ISSUE TITLE
[BUG] marketList 選擇完market後消失

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#746]
選取區在完成選擇後不會消失，必須鼠標移到選擇區以外才會隱藏選擇區。這個問題在 mobile 版會形成非常麻煩的操作體驗，請參考現在 tidebit.com 的操作模式：選擇 markets 後，下拉區立刻自動隱藏

**Comment by TzuHanLiang** [comment]
1 hr

**Comment by royal0721** [comment]
測試結果：
選取
![](https://i.imgur.com/TFh0YsB.png)
選取後
![](https://i.imgur.com/2KmtF36.png)
