### ISSUE TITLE
[BUG] 整體交易界面-orderbooks區域: 精度問題

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#747]
BTC/USDT 和 BTC/USDC 的小數點精度問題還是存在（只需要小數點後一位）

![Image](https://user-images.githubusercontent.com/17249354/184096217-03b04dd4-b981-423b-a37e-1d9a4d82718e.png)

**Comment by TzuHanLiang** [comment]
take 2hrs

**Comment by royal0721** [comment]
20220815 測試未重現
