### ISSUE TITLE
[BUG] OKEx 掛單完成後 MyOrders 掛單消失

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#748]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethusdt)
3.  於限價單買進的第一欄位輸入低於目前市價的數值
4. 第二欄位輸入 0.001
5.  點擊買進
6.  掛單成功
7.  顯示於 My Orders 幾秒後消失

影響範圍： OKEx Trading - 限價買進賣出
## 期待結果
My Orders 更新
![](https://i.imgur.com/XKyjbaS.png)

**Comment by TzuHanLiang** [comment]
跟 #744 是同個原因造成的

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
合併至 #744 驗證

**Comment by royal0721** [comment]
測試結果如下：
測試未重現
![](https://i.imgur.com/FsOB6FX.png)
![](https://i.imgur.com/2GATAiW.png)
