### ISSUE TITLE
[BUG] 整體交易界面-place order區域: 精度問題

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#750]
與 #745 一致
BTC市場存在很麻煩的精度問題：下單處允許 小數點 兩位， My orders 雖然也是兩位，但是截取了一位。 tidebit 數據庫看到是 orders 存的小數點兩位，trades 存的小數點1位，account_versions 使用小數點 2 位。

![Image](https://user-images.githubusercontent.com/17249354/184098100-4dbff41a-87d9-4b8d-a7ee-6dfe2c72045f.png)

**Comment by TzuHanLiang** [comment]
take 1hr

**Comment by royal0721** [comment]
20220822 測試已經修復
![](https://i.imgur.com/FfaJQ75.png)
