### ISSUE TITLE
[BUG] 整體交易界面-place order區域: close 更新速度遲滯

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#751]
市價單下單後，即便最低的下單量，最後的成交價和當前觀察的價格偏差較大（btc大概差幾美元），然後左下角馬上提示已經成交，但是close orders 需要等二十幾秒才能看到數據（我看數據庫確實需要這麼長時間才更新Orders），不確定是orderbooks顯示延遲的問題還是okex那邊的處理問題。

**市價單我們使用的價格： 買*1.1、買*0.9**

**Comment by TzuHanLiang** [comment]
take 5hrs 調整後 在3s的時候發送交易，7s的時候收到交易成功，9s的時候close orders更新
https://user-images.githubusercontent.com/17249354/184847847-e453d6db-9da5-4611-ba0b-0780d643939d.mov

**Comment by royal0721** [comment]
20220817 測試重現

**Comment by royal0721** [comment]
測試結果->未重現
![](https://i.imgur.com/Y2lod6M.png)
![](https://i.imgur.com/QK9gV51.png)
