### ISSUE TITLE
[UI][MOBILE] 部份手機格式不能顯示手機版的介面

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#752]
在 iphone 12/13 pro max 打開 markets 頁面，無法顯示 mobile 版本，iphone 11 pro max 可以正常顯示 mobile 版本。  
safari / chrome/opera 最新版本一樣的效果。

**Comment by TzuHanLiang** [comment]
take 1hr

**Comment by royal0721** [comment]
20220822
需要測試手機進行測試

**Comment by Luphia** [comment]
use Xcode simulator: https://developer.apple.com/documentation/xcode/running-your-app-in-the-simulator-or-on-a-device

**Comment by royal0721** [comment]
20220824 xcode 無法於 App Store 安裝 待 xcode 安裝流程完成

**Comment by royal0721** [comment]
20220829 待 OS 更新

**Comment by royal0721** [comment]
20220830 測試未有重現
13 pro max
![](https://i.imgur.com/ErWB1WB.png)
12 pro max
![](https://i.imgur.com/51ox04m.png)
