### ISSUE TITLE
[BUG] 整體交易界面-my orders區域： order 重複顯示

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#753]
![Image](https://user-images.githubusercontent.com/17249354/184104630-3c88f37c-dcbc-4d13-bce2-ce1cdb20e342.png)

**Comment by TzuHanLiang** [comment]
- take 1hr
  - fixed by passing both DB order id and okex ordId and useing DB order id as id instead of using  okex ordId as order id

**Comment by royal0721** [comment]
20220815 測試未重現

**Comment by Luphia** [comment]
請提供實際測試結果與截圖

**Comment by royal0721** [comment]
實際測試結果截圖：
orders 無重複顯示
![](https://i.imgur.com/tNAHhs8.png)

**Comment by royal0721** [comment]
20220817 測試無法重現此情況
![](https://i.imgur.com/32hNxBk.png)

**Comment by royal0721** [comment]
20220819 測試無法重現
![](https://i.imgur.com/OQ2pVfx.png)

**Comment by TzuHanLiang** [comment]
@royal0721 請幫忙提供測試步驟，或是出現的場景，謝謝。

**Comment by TzuHanLiang** [comment]
- fixed with #767

**Comment by royal0721** [comment]
> @royal0721 請幫忙提供測試步驟，或是出現的場景，謝謝。

1. 掛單成功等待撮合
2. 部分撮合
3. 出現重複 order

但後續未重現

**Comment by royal0721** [comment]
20220822 測試未重現
![](https://i.imgur.com/vyuw6XR.png)
