### ISSUE TITLE
[BUG] test.tidebit.network 不能重設密碼

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#764]
- 因為 recapture 有錯誤無法勾選

**Comment by TzuHanLiang** [comment]
測試結果：
<img width="603" alt="Screen Shot 2022-08-22 at 16 00 33" src="https://user-images.githubusercontent.com/17249354/185871206-32117afb-9d02-4cf9-9640-6d1da0f46840.png">
<img width="1680" alt="Screen Shot 2022-08-22 at 16 05 50" src="https://user-images.githubusercontent.com/17249354/185871214-bdf63c95-bd6c-4f27-863c-e9b7e3079740.png">
![IMG_8428](https://user-images.githubusercontent.com/17249354/185871316-961c7106-86d9-4479-a0de-1120f34e5450.PNG)

**Comment by TzuHanLiang** [comment]
take 1hrs

**Comment by TzuHanLiang** [comment]
<img width="1680" alt="Screen Shot 2022-08-22 at 16 09 10" src="https://user-images.githubusercontent.com/17249354/185871972-6238340a-0d6e-40a3-9168-c4c40064fc55.png">
<img width="1680" alt="Screen Shot 2022-08-22 at 16 09 23" src="https://user-images.githubusercontent.com/17249354/185871984-4a75799e-faa5-4da1-a248-410967d03c05.png">

**Comment by royal0721** [comment]
20220822 測試結果->已經修復
![](https://i.imgur.com/7nNO2va.png)
