### ISSUE TITLE
[BUG] ExchangeHubService sync 不會推通知到前端

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#766]
- 提供 emit bus 的function 給 ExchangeHubService

**Comment by TzuHanLiang** [comment]
take 1hrs

**Comment by TzuHanLiang** [comment]
- has bug, take 1hr to fixed

**Comment by royal0721** [comment]
測試未重現
![](https://i.imgur.com/zzDKWr1.png)
![](https://i.imgur.com/C26e8ak.png)
