### ISSUE TITLE
[BUG] postOrder 更新 account version使用的 reason 錯誤

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#768]
- postOrder 的 reason為 600

**Comment by TzuHanLiang** [comment]
- take 1hrs

**Comment by TzuHanLiang** [comment]
- 驗證辦法
  - post order 後 到DB 確認 剛剛新增的 order reason 為 600

**Comment by royal0721** [comment]
20220822 測試結果為如下 -> 未重現
![](https://i.imgur.com/ThJM2yU.png)
