### ISSUE TITLE
[BUG] OKEx 交易後只會更新一個另一個欄位的 Available amount

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#772]
## 使用功能：
OKEx Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethusdt)
3.  於市價單賣出的第二欄位輸入低於目前市價的數值
4.  點擊賣出
5.  掛單成功
6.  只更新到市價買進欄位的 Available amount，無更新到市價賣出欄位的 Available amount

影響範圍： OKEx Trading - 市價買進賣出

實際結果：

賣出前
![](https://i.imgur.com/yDXMF7k.png)
賣出後
![](https://i.imgur.com/3FqtCdw.png)

資料庫訊息正確 但訊息未推播

**Comment by TzuHanLiang** [comment]
<img width="1679" alt="Screen Shot 2022-08-19 at 15 49 34" src="https://user-images.githubusercontent.com/17249354/185574987-3768343d-4d10-4bc1-8785-27c0d5e9d292.png">
<img width="1679" alt="Screen Shot 2022-08-19 at 15 49 55" src="https://user-images.githubusercontent.com/17249354/185574995-83820af8-32b5-4ef7-b569-5e90762ca3ce.png">
<img width="1679" alt="Screen Shot 2022-08-19 at 15 50 04" src="https://user-images.githubusercontent.com/17249354/185574999-f650096b-3f1c-4db3-b000-b557375266e7.png">
<img width="1679" alt="Screen Shot 2022-08-19 at 15 50 09" src="https://user-images.githubusercontent.com/17249354/185575005-a5a1a8a0-4828-431a-8e3f-648ff689be42.png">

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by royal0721** [comment]
20220819 測試結果如上圖 -> 未重現
