### ISSUE TITLE
[BUG] Tidebit 交易 MyOrders 不會自動更新 

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#774]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  於限價單買進的第一欄位輸入低於目前市價的數值
4. 第二欄位輸入隨機掛單數
5.  點擊買進
6.  掛單成功
7.  MyOrders 不會自動更新
8. 刷新後更新

影響範圍： Tidebit Trading - 限價市價買進賣出

## 期待結果
MyOrders 自動更新

## 實際結果
交易前
![](https://i.imgur.com/JW3WWXg.png)

交易後
![](https://i.imgur.com/QBTUKvt.png)

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by TzuHanLiang** [comment]
測試結果
https://user-images.githubusercontent.com/17249354/185614488-da66442b-e0fc-4f90-a829-be5f3478991a.mov

**Comment by royal0721** [comment]
20220824 測試結果 -> 未重現
![](https://i.imgur.com/0b0Mc9i.png)
![](https://i.imgur.com/3dxub3R.png)
