### ISSUE TITLE
[BUG] Tidebit 交易 Available Amount 不會自動更新

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#775]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  於限價單買進的第一欄位輸入低於目前市價的數值
4. 第二欄位輸入目前市價的掛單數
5.  點擊買進
6.  掛單成功
7.  Available Amount 不會自動更新
8. 刷新後更新

影響範圍： Tidebit Trading - 限價市價買進賣出

## 期待結果
Available Amount 自動更新
## 實際結果
交易前
![](https://i.imgur.com/RTh27eM.png)
交易後
![](https://i.imgur.com/jBHX2p7.png)

**Comment by TzuHanLiang** [comment]
- fixed by #774

**Comment by royal0721** [comment]
20220822 測試重現
![](https://i.imgur.com/fI3zIKg.png)
![](https://i.imgur.com/VbEyhlN.png)

**Comment by royal0721** [comment]
20220824 測試重現 -> 僅有單邊更新
交易前
![](https://i.imgur.com/g8cullm.png)
交易後
![](https://i.imgur.com/Fh4naNP.png)
交易後 balance對照
![](https://i.imgur.com/pmGPZoV.png)

**Comment by royal0721** [comment]
20220826  測試重現
交易後 balance對照
![](https://i.imgur.com/m49sT0H.png)

**Comment by royal0721** [comment]
20220829 測試重現
交易後 balance對照
![](https://i.imgur.com/pmWvHG2.png)

**Comment by TzuHanLiang** [comment]
take 2hr

**Comment by royal0721** [comment]
測試未重現
![](https://i.imgur.com/VJQnM08.png)

**Comment by TzuHanLiang** [comment]
- bug 原因：
  -  我在 src/components/MarketTade.js 裡面使用 account 的 balane 時 我有額外使用 useState 去存 storeCtx 裡面 account 的資料，導致更新不同步。
