### ISSUE TITLE
[BUG] Tidebit 無法部分撮合成功

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#776]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  於市價單買進的第二欄位高於市場深度的 amount 
4.  點擊買進
5.  無法掛單成功

影響範圍： Tidebit Trading - 市價買進賣出

## 期待結果
掛單成功

## 實際結果
![](https://i.imgur.com/KkW2twZ.png)

**Comment by TzuHanLiang** [comment]
測試結果


https://user-images.githubusercontent.com/17249354/185614745-97f96cb2-90b6-4af8-9080-a7256920274e.mov

**Comment by TzuHanLiang** [comment]
- 一次交易額度不能超過市場深度的 1/10。
