### ISSUE TITLE
[UI]交易介面補上用戶資訊

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#780]
- 用戶email
- preference 選單
  - 聲效
  - 通知
  - funds
  - history
  - profile
  - logout
- 用戶餘額

![Image](https://user-images.githubusercontent.com/17249354/185856833-9cc38b48-b8cd-4a21-bf0d-bba4e89f6219.png)

**Comment by TzuHanLiang** [comment]
- 總資產還沒取得， remain 1hrs

**Comment by royal0721** [comment]
20220829 尚未顯示總資產
![](https://i.imgur.com/JjXD9KM.jpg)

**Comment by royal0721** [comment]
20220831 測試未修復
![](https://i.imgur.com/jmjEbUd.png)

**Comment by TzuHanLiang** [comment]
take 1.5hr

**Comment by royal0721** [comment]
20220901 測試於交易後會更新
![](https://i.imgur.com/Z8xRgE0.png)

**Comment by TzuHanLiang** [comment]
- bug 原因：
  -  backend/libs/AccountBook.js 在呼叫 getDifference 的方法時，沒有吧 priceList（匯率資料，帶進 account 裡面） 導致前端無法計算總金額

**Comment by Luphia** [comment]
Fix with #824
