### ISSUE TITLE
[BUG][Mobile] MyOrders 要顯示

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#781]
![Image](https://user-images.githubusercontent.com/17249354/185857879-755f3a4f-d3af-472d-a0e0-8ef1dc9fab22.png)

**Comment by TzuHanLiang** [comment]
take 2hrs

**Comment by Luphia** [comment]
fix with #793

**Comment by royal0721** [comment]
20220829 測試有顯示交易紀錄和市場
![](https://i.imgur.com/mV5lUFY.png)
