### ISSUE TITLE
[BUG][Mobile] 虛擬鍵盤不能使用

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#782]
- 鍵盤按了沒有反應
- 後推薦圖片沒有顯示
- 關閉按鈕 x 沒有置中
![Image](https://user-images.githubusercontent.com/17249354/185858578-b97de852-7c95-456e-ad96-df9d2ce4dd8a.png)

**Comment by TzuHanLiang** [comment]
take 3hrs

**Comment by Luphia** [comment]
fix with #793

**Comment by royal0721** [comment]
20220829 Samsung S21 FE 測試無重現
![](https://i.imgur.com/62731AX.png)

**Comment by TzuHanLiang** [comment]
- fixed by #797
