### ISSUE TITLE
[BUG] fetchTradeFillsHistory 要問到指定的時間

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#789]
- okex 限制是回傳100筆
- 所以有給時間range 如果超過100筆 api也不會拿到

**Comment by TzuHanLiang** [comment]
take 4hrs

**Comment by Luphia** [comment]
- 需完成時間設定介面方可驗證

**Comment by TzuHanLiang** [comment]
take 10mins

**Comment by TzuHanLiang** [comment]
- api 需要修改成根據指定開始及結束的時間拿對應的資料

**Comment by TzuHanLiang** [comment]
- 這個資料是來自DB
- DB 的資料是 ExchangeHubServices 定期從 OKEx sync 得到的
  - 在 services 一啟動的時候會先拿近 3 個月的交易資料（okex的限制，最舊的是近三個月的資料）
- 新增 DB query
  - getOuterTradesBetweenDays
- remain 確認 ExchangeHubServices 有完整 sync 到可以得到的最舊及最新的資料， remain 1hrs

**Comment by Julian0701** [comment]
使用[TBETC000001](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000001_%E6%92%AE%E5%90%88%E6%88%90%E4%BA%A4%E7%B4%80%E9%8C%84.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000001 撮合成交紀錄查詢](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000001/20221104.md)驗證通過
