### ISSUE TITLE
[BUG] MarketTrade 價格與數量輸入邏輯調整

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#797]
輸入小於精度的位數時，不用理會，不要四捨五入

**Comment by TzuHanLiang** [comment]
- take 3-4hrs

**Comment by royal0721** [comment]
20220908 測試未重現

<img width="1440" alt="Screen Shot 2022-09-08 at 4 23 45 PM" src="https://user-images.githubusercontent.com/29693123/189073388-cb2fc9e6-a219-4c79-923c-af81d6779e69.png">
<img width="1440" alt="Screen Shot 2022-09-08 at 4 23 59 PM" src="https://user-images.githubusercontent.com/29693123/189073395-3c636700-9022-47cc-ae6b-3320984b6cb1.png">
<img width="1440" alt="Screen Shot 2022-09-08 at 4 22 17 PM" src="https://user-images.githubusercontent.com/29693123/189073371-e5c36b66-2cc5-45f1-a5f8-ac81510e2d8a.png">
