### ISSUE TITLE
[BUG][Mobile] 數字鍵盤邏輯調整

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#798]
- 輸入不流暢
- 虛擬鍵盤 input 邏輯不同於網頁版鍵盤輸入
  - 輸入一樣的內容會有不同的結果

**Comment by TzuHanLiang** [comment]
- take 3hrs

**Comment by TzuHanLiang** [comment]
take 2hrs

**Comment by royal0721** [comment]
20220908 測試結果 -> 未重現
https://user-images.githubusercontent.com/29693123/189072509-5916d654-543a-43a6-8bd3-115661abb1bb.mp4
