### ISSUE TITLE
[ENHANCE] 撮合成交紀錄頁面調整

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#800]
不包含`撮合毛利走勢圖`#812 及`Date Picker`#813
<img width="1680" alt="Screen Shot 2022-08-29 at 17 48 38" src="https://user-images.githubusercontent.com/17249354/187174373-7bbaf392-1577-4f9b-9767-bad7729bd929.png">
<img width="1680" alt="Screen Shot 2022-08-29 at 17 48 43" src="https://user-images.githubusercontent.com/17249354/187174387-e48f519c-49dc-4232-9be8-246ef4c11b5b.png">
<img width="1680" alt="Screen Shot 2022-08-29 at 17 48 47" src="https://user-images.githubusercontent.com/17249354/187174395-6cb7a610-a7ee-4978-a82f-7bf5976761d3.png">

**Comment by TzuHanLiang** [comment]
take 3hrs

**Comment by royal0721** [comment]
20220831 測試如下->已完成
![](https://i.imgur.com/4gynRkA.png)
![](https://i.imgur.com/moZ8g6j.png)
