### ISSUE TITLE
[BUG] 交易彈跳視窗出現NAN值

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#801]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  於市價單買進的第二欄位等於市場深度的 amount 
4.  點擊買進
5.  彈跳視窗出現 NAN 值

影響範圍： Tidebit Trading - 市價買進賣出

## 期待結果
![](https://i.imgur.com/rqVfFqc.png)

**Comment by royal0721** [comment]
20220830 測試未重現
![](https://i.imgur.com/zHHPXqp.png)

**Comment by TzuHanLiang** [comment]
take 1hr
