### ISSUE TITLE
[ENHANCE] 實作權限管理

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#803]
- 登入帳號要符合 admin 才能觀看該介面
  - 需要一個頁面或是 dialog 對沒有admin權限的 user 顯示不可訪問，請申請升級權限之類的

**Comment by TzuHanLiang** [comment]
- take 1.5hr
  -  remain 頁面提示及功能確認，約 2-3hrs

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by Julian0701** [comment]
使用[TBETC000002](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000002_%E7%AE%A1%E7%90%86%E6%AC%8A%E9%99%90%E5%B8%B3%E8%99%9F.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000002 管理權限帳號功能](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000002)驗證完成
