### ISSUE TITLE
[BUG] 掛單交易彈出視窗語言未同步

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#806]
## 重現步驟
1. 以一般的使用者帳號登入
2. 進入 trading 頁面
3. 隨意進行一筆限價單掛單 （要在 amount 範圍內）
4. 彈跳視窗文字語言（英文）與網站語言不同（中文）
## 期待結果
語言顯示相同 
## 實際結果
![](https://i.imgur.com/zHHPXqp.png)

**Comment by royal0721** [comment]
20220831 測試未修復
![](https://i.imgur.com/moZ8g6j.png)

**Comment by TzuHanLiang** [comment]
> 20220831 測試未修復 ![](https://camo.githubusercontent.com/ed059eff1f1d24338f5df3d9f9394a040b77e42939d58ab783dd5404fa714182/68747470733a2f2f692e696d6775722e636f6d2f6d6f5a3867366a2e706e67)

是不是放錯資料了？

**Comment by royal0721** [comment]
> > 20220831 測試未修復 ![](https://camo.githubusercontent.com/ed059eff1f1d24338f5df3d9f9394a040b77e42939d58ab783dd5404fa714182/68747470733a2f2f692e696d6775722e636f6d2f6d6f5a3867366a2e706e67)
> 
> 是不是放錯資料了？
> 
是的 我貼錯截圖  晚點測試時間補上

**Comment by TzuHanLiang** [comment]
take 2hrs

**Comment by royal0721** [comment]
20220901 測試結果如下->出現 {{baseunit}} 未完全修復
![](https://i.imgur.com/Z8xRgE0.png)

**Comment by royal0721** [comment]
20220908 測試未重現
<img width="1440" alt="Screen Shot 2022-09-08 at 4 22 17 PM" src="https://user-images.githubusercontent.com/29693123/189073022-4a53f229-fe40-4b96-9e61-5a7b68dfb0e5.png">
