### ISSUE TITLE
[BUG] getOuterTradeFills & getOuterPendingOrders 邏輯調整

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#807]
- 這兩個 api 分別使用來顯示`撮合成交記錄查詢`及`當前掛單記錄查詢`的api
- 這兩個api 都有分別直接從DB 拿全部的members 資料及全部的 orders 資料，非常耗效能
- 調整方法
  - 在 process 完 outer_trades 時，除了更新 status，也把對應的 memberId（或是memberId、fee_rate 及 email）還有 order ID（或是 order price）也寫上

**Comment by TzuHanLiang** [comment]
take 4hrs

**Comment by royal0721** [comment]
20220901 測試未有重現
![](https://i.imgur.com/PnhhGeV.png)
