### ISSUE TITLE
[ENHANCE]  當前掛單記錄查詢頁面調整

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#808]
![Image](https://user-images.githubusercontent.com/17249354/187418754-5ed25608-119f-4075-b575-a6a4681feb98.png)

**Comment by TzuHanLiang** [comment]
take 3hrs

**Comment by royal0721** [comment]
20220831 測試已完成
![](https://i.imgur.com/jmjEbUd.png)
