### ISSUE TITLE
[ENHANCE] 推薦手續費新增到撮合紀錄頁面

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#814]
與 #673 相關，我們不處理，但Tibit-legacy daemons 有處理
- table `referral_commissions` 可以查到推薦手續費

**Comment by TzuHanLiang** [comment]
- take 3hrs 
- 發現新 issue [#825](https://github.com/CAFECA-IO/TideBitEx/issues/825)

**Comment by Julian0701** [comment]
使用[TBETC000007](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000007_%E6%8E%A8%E8%96%A6%E4%BA%BA%E4%BA%A4%E6%98%93%E5%9B%9E%E9%A5%8B%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000007 推薦人交易回饋功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000007/20221031.md)驗證不通過

**Comment by Julian0701** [comment]
於[TBETC000007 推薦人交易回饋功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000007/20221104.md)驗證不通過

**Comment by TzuHanLiang** [comment]
@Luphia 這段 code 是 comment 起來的狀態

**Comment by Julian0701** [comment]
於[TBETC000007 推薦人交易回饋功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000007/20221111.md)驗證通過

**Comment by Julian0701** [comment]
於[TBETC000007 推薦人交易回饋功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000007/20221111.md)驗證通過
