### ISSUE TITLE
[BUG] 手機交易介面多次切換分頁會發生空白畫面

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#819]
- 不應該出現這種問題

**Comment by TzuHanLiang** [comment]
- take 1hr 將畫面點擊的error 修除，要更新到 new.tidebit.com 後驗證

**Comment by royal0721** [comment]
20220905 測試未有重現 -> 未出現空白畫面
![](https://i.imgur.com/NWeTkPQ.png)
![](https://i.imgur.com/aUrwWPQ.png)
