### ISSUE TITLE
[BUG] 手機介面點擊市場應跳轉到交易介面

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#820]
- 手機介面點擊市場應有時候會沒有反應，需要多次點擊
- 目前在 BTC/USDT交易對最明顯

**Comment by TzuHanLiang** [comment]
9/7 take 5hrs

**Comment by TzuHanLiang** [comment]
9/12 補功能實作

**Comment by TzuHanLiang** [comment]
take 1hr

**Comment by Julian0701** [comment]
使用[TBETC000003](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000003_%E6%89%8B%E6%A9%9F%E7%89%88%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000003 使用者介面管理](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000003)驗證通過
