### ISSUE TITLE
[BUG] processOuter Error if outerOrder filled by multiple trade will get Error

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#822]
- 當外部交易是由多筆trade 來撮合時，更新會出錯，出錯的原因為部份撮合時也把 order 的 state 直接改為 200(done)及 locked 改為0， 導致後續更新出錯

![Image](https://user-images.githubusercontent.com/17249354/188083224-a47dcb96-5c29-47de-a10e-6012a377eb55.png)

![Image](https://user-images.githubusercontent.com/17249354/188083708-4867deef-1f8a-4d99-8f16-c616dd106b25.png)

**Comment by TzuHanLiang** [comment]
- 此情況不容易再現，後續將持續追蹤

**Comment by royal0721** [comment]
20220905 不確定是否有權限可以進行測試

**Comment by royal0721** [comment]
20220908 缺乏權限進行測試
