### ISSUE TITLE
[BUG] Tidebit Trading 皆不會更新 DepthBook 

### ISSUE THREAD

**Issue by royal0721** [CAFECA-IO/TideBitEx#828]
## 使用功能：
Trading 
## 狀況重現步驟：
1. 使用已驗證的帳號登入
2.  進入[trading頁面](https://test.tidebit.network/markets/ethhkd)
3.  於限價單買進的第一欄位等於市價的價格 
4.  於第二欄位輸入 available amount 以下的數值
5.  點擊買進
6.  掛單成功
7.  DepthBook 不會更新 刷新後也不會更新

影響範圍： Tidebit Trading - 限價市價買進賣出
![](https://i.imgur.com/OmPbG2z.png)

**Comment by TzuHanLiang** [comment]
參考 #829 (https://github.com/CAFECA-IO/TideBitEx/issues/829) ，出錯原因為db 裡面存在該被取消但是沒有被取消的 ioc 交易單

**Comment by royal0721** [comment]
20220908 測試 DepthBook 有更新
掛單前
![](https://i.imgur.com/siwAHcn.png)
掛單後
![](https://i.imgur.com/dKLIXKy.png)
![](https://i.imgur.com/qN4oqN3.png)
