### ISSUE TITLE
OKEx trading event syncer

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/TideBitEx#84]
WebSocket API 與Rest API 新增介面與DB互動

---

更新訂單拆分

- [x] #179
- [x] #171
- [x] #172
- [x] #173
- [x] #174
- [x] #175
- [x] #176

**Comment by Luphia** [comment]
- update user balance and lock assets after place order
- update user balance and lock assets after cancel order
- update user balance and lock assets after trading

**Comment by Waiting4Ever** [comment]
對應的table
- order
  - orders
  - vouchers

**Comment by Waiting4Ever** [comment]
異動class
- Bot.ExchangeHub.postPlaceOrder
- Bot.ExchangeHub.getOrderList
- Bot.ExchangeHub.postCancelOrder
異動 WebSocket API
- _updateTrades
- _updateBooks
- _updateCandle1m
- _updateTickers

**Comment by Waiting4Ever** [comment]
現在update order尚未完成

**Comment by Waiting4Ever** [comment]
create order used 8 hr
cancel order used 2 hr
update order used 2.5 hr, remains 4 hr

**Comment by Luphia** [comment]
- Function Done
