### ISSUE TITLE
[後台管理][頁面功能] 權限管理

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#840]
#497 的頁面功能

**Comment by TzuHanLiang** [comment]
take 3hrs

**Comment by TzuHanLiang** [comment]
- take 3hrs 因修改api而調整

**Comment by Julian0701** [comment]
使用[TBETC000002](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000002_%E7%AE%A1%E7%90%86%E6%AC%8A%E9%99%90%E5%B8%B3%E8%99%9F.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000002 管理權限帳號功能](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000002)驗證通過
