### ISSUE TITLE
[DOC] 補充 addAdminUser、deleteAdminUser、updateAdminUser API 文件

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#844]
- [文件位置](https://github.com/CAFECA-IO/TideBitEx/wiki/backend-API-v1-Admin)
- 補上 response

**Comment by TzuHanLiang** [comment]
- take 1.5hrs [文件位置](https://github.com/CAFECA-IO/TideBitEx/wiki/backend-API-v1-Admin)

**Comment by TzuHanLiang** [comment]
- response payload 裡面不需要再有一個 result， 使用 response 裡面的success， remain 30mins

**Comment by Luphia** [comment]
checked
