### ISSUE TITLE
[BUG][後台頁面] 沒有權限的 User 訪問時有時沒有觸發跳轉到登錄

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#850]
- 手機上沒有權限的 User 進入/analysis後被提出，在直接使用下一頁的話會沒有觸發到 useEffect

**Comment by TzuHanLiang** [comment]
- take 1hr

**Comment by Julian0701** [comment]
使用[TBETC000003](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000003_%E6%89%8B%E6%A9%9F%E7%89%88%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000002 管理權限帳號功能](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000002)驗證通過
