### ISSUE TITLE
TideBitEx 0.8.13 hotfix

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#858]
- v0.8.12 交易後資料更新異常，不定期出現資料漏更新的問題
- new.tidebit.com 連的 ws domain 不一樣缺少 cookie 資料導致 tidebit slagger private channel 註冊失敗
  - 使用別的方式取得資料

**Comment by Julian0701** [comment]
使用[TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000006_%E4%BA%A4%E6%98%93%E7%95%8C%E9%9D%A2%E7%9A%84%E5%8D%B3%E6%99%82%E6%9B%B4%E6%96%B0%E6%AA%A2%E9%A9%97.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000006 交易界面的即時更新檢驗](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000003/20221028.md)驗證通過
