### ISSUE TITLE
[後台管理][出入金管理] 整理coins.yml 每個幣種需要分別新增出入金手續費，資料到 markets.yml 上查找

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#859]
- 先找到  tidebit-lagacy 是吃哪份檔案來判斷可以入金的幣種
- 再根據 tidebit-lagacy markets.ymls 及  tidebit-lagacy coins.yml

**Comment by TzuHanLiang** [comment]
- Tidebit-lagacy 出入金相關資料整理 [doc](https://github.com/CAFECA-IO/Documents/blob/main/TBE/TBESV00004.md)
- take 3hrs

**Comment by TzuHanLiang** [comment]
-take 1hr 已補充

**Comment by TzuHanLiang** [comment]
- take 2hrs 已補充

**Comment by Julian0701** [comment]
使用[TBETC000004](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000004_%E5%87%BA%E5%85%A5%E9%87%91%E6%89%8B%E7%BA%8C%E8%B2%BB%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000004 出入金手續費管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000004/20221031.md)驗證通過
