### ISSUE TITLE
/accounts 要根據coins.yml開啟或關閉出入金功能

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#861]
- 推測更改 coins.yml 可以控制 /accounts 列表上的 coins 顯示
![Image](https://user-images.githubusercontent.com/17249354/191227761-5d884f6f-05d6-4fea-b8e1-1d94915d8a55.png)

**Comment by TzuHanLiang** [comment]
- 經測試，推測有誤，需在找其他方法

**Comment by TzuHanLiang** [comment]
- 修改 coins.yml 後 先測試重開 Tidebit-Lagacy 確認 /accounts 的 coins 列表是吃這個yaml當
- 根據 [doc](https://github.com/CAFECA-IO/Documents/blob/main/TBE/TBESV00004.md) 去找 是不是 coins 拿取之後就存在 storage 裡不會重新拿
- 若是這樣的話，需要在 Tidebit-Lagacy  新增在render /accounts 的 coins 列表之前 重新讀取  coins.yml  的動作

**Comment by TzuHanLiang** [comment]
- 經測試 修改 coins.yml 或是 deposts.yml 後 重開 Tidebit-Lagacy 確認 /accounts 的 coins 列表是吃這個yaml檔

**Comment by TzuHanLiang** [comment]
- 修改方式 
- 在 TideBit-Lagacy/app/controllers/private/accounts_controller.rb ln24-ln26 新增下面 3 行
```
      Currency.reload(true)
      DepositChannel.reload(true)
      WithdrawChannel.reload(true)
```
- 潛在風險
如果修改完後，沒有觸發到 AccountController 就不會觸發 reload 所以環境中其他位置拿到的可能還是舊資料

**Comment by TzuHanLiang** [comment]
- 做法 
- 在 TideBit-Lagacy/app/controllers/private/accounts_controller.js ln24-27 新增：
```
      Rails.logger.warn "Reload!!!!"
      Currency.reload(true)
      DepositChannel.reload(true)
      WithdrawChannel.reload(true)
```
- 潛在風險：
  - 上面的 code 只有在 render /accounts 的時候會觸發 AccountsController，所以如果環境中有在沒觸發上列 code 的情況下取得當下 Currency、DepositChannel、WithdrawChannel的資料的話，會取到舊的資料。
    - ex： 
      - api
      - db

**Comment by TzuHanLiang** [comment]
- 需要改 TideBit-Lagacy

**Comment by Julian0701** [comment]
使用[TBETC000004](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000004_%E5%87%BA%E5%85%A5%E9%87%91%E6%89%8B%E7%BA%8C%E8%B2%BB%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000004 出入金手續費管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000004/20221031.md)驗證通過
