### ISSUE TITLE
[Enhance][出入金管理](需討論) 功能串接

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#862]
- 使用 coins.yml 將幣種 render 處理
- 目前缺少部份資料
  - 交易所選項
  - 外部入金手續費（定義需確認： 外部入金是指我們入金到其他交易所得成本嗎？例如我們把錢轉到 okex 的手續費，那這樣的話，這個成本就不是我們可以設定的，或是是會有最低值的）
  - 內部入金手續費
  - 外部出金手續費
![Image](https://user-images.githubusercontent.com/17249354/191392886-4d07cc7e-16a6-4929-98cf-2403472f2902.png)

**Comment by TzuHanLiang** [comment]
- remain 1.5hrs
  -  update status api 有錯誤
  -  update fee 數字的 formating

**Comment by Julian0701** [comment]
使用[TBETC000004](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000004_%E5%87%BA%E5%85%A5%E9%87%91%E6%89%8B%E7%BA%8C%E8%B2%BB%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000004 出入金手續費管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000004/20221031.md)驗證通過
