### ISSUE TITLE
[UI][出入金管理設定] UI 調整

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#864]
- 出入金的手續費不分當前與外部
  - value UI 調整
  - 跳出式選單 UI 調整
- 全部開啟/全部關閉的功能不需要，並將 title 改成顯示
- 新增兩個可調節的開關，入金功能的開啟及關閉、出金功能的開啟及關閉

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by Julian0701** [comment]
使用[TBETC000004](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000004_%E5%87%BA%E5%85%A5%E9%87%91%E6%89%8B%E7%BA%8C%E8%B2%BB%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000004 出入金手續費管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000004/20221031.md)驗證通過
