### ISSUE TITLE
[Backend] API updateTickerMakerFee & updateTickerTakerFee 實作

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#870]
- 透過 API 更新
  - Tidebit-Legacy/config/markets/markets.yml
- 更新 tickerBook tickersSettings
- 需實際在 TideBit-Lagacy 的環境做實驗，確認是如何收手續費的，是否有分 taker 、 maker還是真的以 bid 、ask 來收手續費， 實驗前需先與 @Luphia 確認實驗方案

**Comment by TzuHanLiang** [comment]
- take 1hr
- remain 2hrs
  - 測試未實作
    - 約 2hrs

**Comment by TzuHanLiang** [comment]
- 實驗：
  - 定義 
   - 先掛單被撮合的單為 Maker 單
   - 後掛單撮合其他單的單為 Taker 單
 - 方法
   - 選擇 btc/hkd
   - 將 markets/markets.yml btc/hkd ask 及 bid 的 fee 分別改成 0.1 及 0.2
   - 做兩筆交易
     - 先以 bid 0.1 btc 以 110 usdt 的價格，再以 ask 0.1 btc 以 100 usdt 的價格
     - 先以 ask 0.1 btc 以 100 usdt 的價格，再以 bid 0.1 btc 以 110 usdt 的價格
   - 到 DB 去看上訴兩筆交易分別收取的手續費為多少

**Comment by TzuHanLiang** [comment]
- take 1.5hrs 測試
- 是使用  btc/hkd 交易對  ask 及 bid 的 fee 分別為 0.0012 及 0.003
- 做四筆交易（已按先後順序排序）  
<img width="1680" alt="Screen Shot 2022-10-06 at 18 20 10" src="https://user-images.githubusercontent.com/17249354/194288996-19e511c2-b3d1-49cb-bded-669d977619c8.png">
- 得到四筆 vouchers 紀錄 （根據 order 排序）
<img width="1680" alt="Screen Shot 2022-10-06 at 18 21 18" src="https://user-images.githubusercontent.com/17249354/194289247-d5574b9b-03d3-45ce-8b97-ace5e6f6ac06.png">

可以由上面截圖得知， TideBit-Lagacy 交易手續費收取方式不是以 Taker 及 Maker 劃分，而是由 Ask 及 Bid 劃分。

**Comment by TzuHanLiang** [comment]
- [api 文件已補](https://github.com/CAFECA-IO/TideBitEx/wiki/backend-API-v1-Admin)

**Comment by Julian0701** [comment]
使用[TBETC000008](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000008_%E6%88%90%E4%BA%A4%E6%89%8B%E7%BA%8C%E8%B2%BB%E8%B2%BB%E7%8E%87%E8%AA%BF%E6%95%B4.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000008 成交手續費費率調整](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000008/20221031.md)驗證不通過

**Comment by TzuHanLiang** [comment]
2022/11/02 由 #985 處理， @Julian0701  請問相關測試結果文件在那裡可以看到？

**Comment by Julian0701** [comment]
於[TBETC000008 成交手續費費率調整](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000008)驗證通過
