### ISSUE TITLE
[Frontend] 交易對管理功能四隻 API 串接

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#871]
- 將 交易對管理功能 頁面上的假資料 改成串接 API
- 實作 Ticker 開啟關閉功能
- 實作 Fee 更新功能
- 實作 Source 更新功能

**Comment by TzuHanLiang** [comment]
- take 3hrs

**Comment by TzuHanLiang** [comment]
- [api 文件已補](https://github.com/CAFECA-IO/TideBitEx/wiki/backend-API-v1-Admin)

**Comment by Julian0701** [comment]
使用[TBETC000008](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000008_%E6%88%90%E4%BA%A4%E6%89%8B%E7%BA%8C%E8%B2%BB%E8%B2%BB%E7%8E%87%E8%AA%BF%E6%95%B4.md)驗證

**Comment by TzuHanLiang** [comment]
@Julian0701  請問相關測試結果文件在那裡可以看到？

**Comment by Julian0701** [comment]
是這一項[TBETC000008](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000008/20221031.md)

**Comment by Julian0701** [comment]
於[TBETC000008 成交手續費費率調整](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000008)[](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000008/20221104.md)驗證通過
