### ISSUE TITLE
[Frontend] 交易對管理功能UI新增 及 css 微調

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#872]
- 新增 Ticker Fee Update Dialog
<img width="702" alt="Screen Shot 2022-09-26 at 19 58 56" src="https://user-images.githubusercontent.com/17249354/192270886-9afd83f7-ae5b-43d3-8530-01198e1a19c1.png">

- 交易對管理 fee 欄位將 `當前` 、 `外部` 改成 `Default` 、 `Hero`、`VIP`
<img width="332" alt="Screen Shot 2022-09-26 at 19 59 05" src="https://user-images.githubusercontent.com/17249354/192270926-eb164969-9c82-4fa2-8f73-e79604659260.png">

**Comment by TzuHanLiang** [comment]
take 3hrs

**Comment by Julian0701** [comment]
使用[TBETC000008](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000008_%E6%88%90%E4%BA%A4%E6%89%8B%E7%BA%8C%E8%B2%BB%E8%B2%BB%E7%8E%87%E8%AA%BF%E6%95%B4.md)驗證
