### ISSUE TITLE
[BUG][UI]Btc 下單提示（0.00001btc） 和 真實限制（0.001btc）不一致

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#876]
Btc 下單提示（0.00001btc） 和 真實限制（0.001btc）不一致。
<img width="415" alt="image" src="https://user-images.githubusercontent.com/17249354/192206520-ac9bd449-e0ff-4c17-9e9e-bd2bb3158fe2.png">

**Comment by Luphia** [comment]
checked

**Comment by Julian0701** [comment]
使用[TBETC000005_](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221111.md)驗證通過
