### ISSUE TITLE
[BUG]已經撮合成功的 order 至少會延遲20秒以上才會更新狀態

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#877]
撮合成交的數據延遲非常嚴重。 下單成功後，觀察 orderbook 區order更新，在已經觸碰到限價單價格後，【我的委託】 區顯示數據延遲非常嚴重。不完全統計，已經撮合成功的 order 至少會延遲20秒以上才會更新狀態。

**Comment by TzuHanLiang** [comment]
- 做法
  1. remove workaround
  2. 新增 ws 收到通知後直接通知前端
  3. 接續原本流程 ExchangeHubServices.sync()
  4. orderBook 修改判斷是否為需要通知前端的 function 調整，避免重複通知

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221111.md)驗證通過
