### ISSUE TITLE
[BUG]已經撮合成功的 order 在UI上可以被取消，但並沒有實際取消

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#878]
和#877有關：在明明已經觸達限價單價格後，由於【我的委託】限價單還存在，此時取消訂單，等很長時間，限價單在【我的委託】消失，在【歷史委託】出現，但是狀態異常：可以在【訂單記錄】看到 order 已經“完成”，但是在 【歷史委託】看到是“Canceled”（還有，這個需要與語言設置同步）。而如果刷新交易介面，【歷史委託】看到是“Done”（這個需要與語言設置同步）。
![image](https://user-images.githubusercontent.com/17249354/192206746-38bee40e-ecaf-4ca4-a2ba-d467a67bbe41.png)
<img width="415" alt="image" src="https://user-images.githubusercontent.com/17249354/192206764-9fb07fb5-d8c9-463c-9552-53f702a9e479.png">
<img width="415" alt="image" src="https://user-images.githubusercontent.com/17249354/192206775-2eb0f2bc-01cb-45ca-9b8e-88c65ee804d2.png">

**Comment by TzuHanLiang** [comment]
- fixed by #922 #877

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能檢驗](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221031.md)驗證通過
