### ISSUE TITLE
[BUG]`市場價格`，K線最新價格和`最新成交`的數據還是無法一致 

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#880]
“市場價格”，K線最新價格和“最新成交”的數據還是無法一致，尤其 K 線的最新價格，更新狀態還是不穩定。
![image](https://user-images.githubusercontent.com/17249354/192269151-486beb86-f0c6-40e7-8574-ee84cc4e65f9.png)

**Comment by TzuHanLiang** [comment]
- 將前端收到 tickers 及 trades 後即時更新到頁面上
因為 tradingView ws 來源與交易頁面的 tickers 及 trades 是不一樣的，所以兩者均以第三方更新的頻率更新

**Comment by Julian0701** [comment]
使用[TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000006_%E4%BA%A4%E6%98%93%E7%95%8C%E9%9D%A2%E7%9A%84%E5%8D%B3%E6%99%82%E6%9B%B4%E6%96%B0%E6%AA%A2%E9%A9%97.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000006 交易界面的即時更新檢驗](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000003/20221028.md)驗證通過
