### ISSUE TITLE
[doc] TideBit 用戶行為整理

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#889]
- TideBit 用戶行為
   - 什麼行為會影響錢，影響了誰的錢

**Comment by TzuHanLiang** [comment]
- take 0.5hrs
  - [doc 初版](https://github.com/CAFECA-IO/Documents/blob/main/TBE/TBEOP00002.md)

**Comment by TzuHanLiang** [comment]
- take 0.5hrs 改版，改後需要再修改，需要將使用的的數字用變數表示。
- 預計還需 0.5hrs 調整

**Comment by TzuHanLiang** [comment]
- take 1.5hr

**Comment by Luphia** [comment]
- require range interval

**Comment by TzuHanLiang** [comment]
- add range interval take 0.5hr
