### ISSUE TITLE
[UI][TideBit-Market] 選擇交易市場的分類排序及分類名稱調整

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#906]
![Image](https://user-images.githubusercontent.com/17249354/194206652-a95e91ac-fb45-4008-bba2-58d23a06c972.jpg)

**Comment by TzuHanLiang** [comment]
take 1hr

**Comment by Julian0701** [comment]
使用[TBETC000003](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000003_%E4%BD%BF%E7%94%A8%E8%80%85%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000003 使用者介面管理](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000003)驗證通過
