### ISSUE TITLE
[Config] ETH/USDT、BTC/USDT 小數精度調整成與 OKX 一致

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#907]
- 原先是將 TideBit-Lagacy/config/markets/markets.yml 與 OKX 的精度去比較，兩者取大，改成 source 為 OKX 取 OKX 的精度

**Comment by TzuHanLiang** [comment]
- MarketTrade 
  - formatSize function 最小交易 size 由原本的 lotSz 改完 minSz 因為 Okx minSz 可能會大於 lotSz（之所以原本用 lotSz 是因為  TideBit-Lagacy/config/markets/markets.yml  裡面設定的精度 大於  Okx minSz）

**Comment by Julian0701** [comment]
使用[TBETC000003](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000003_%E4%BD%BF%E7%94%A8%E8%80%85%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000003 使用者介面管理](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000003)驗證通過
