### ISSUE TITLE
[Config] 手續費費率調整

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#909]
- 費率方面，okx 收我們maker taker 0.06/ 0.08，他們標準是0.08/0.1，所以我們給客戶也是 0.08/0.1
  -  所有交易對全改
  -  VIP Hero 費率也需一致
  - 需先完成 #870 的實驗，根據實驗結果修改

**Comment by TzuHanLiang** [comment]
- 更新成所有手續費都設成 0.1%，新的yml已提供
- take 1hrs

**Comment by Julian0701** [comment]
使用[TBETC000008](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000008_%E6%88%90%E4%BA%A4%E6%89%8B%E7%BA%8C%E8%B2%BB%E8%B2%BB%E7%8E%87%E8%AA%BF%E6%95%B4.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000008 成交手續費費率調整](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000008/20221031.md)驗證不通過

**Comment by TzuHanLiang** [comment]
2022/11/02 由 #985 處理， @Julian0701  請問相關測試結果文件在那裡？

**Comment by Luphia** [comment]
- Ignore Staging Environment
