### ISSUE TITLE
[BUG][UI] 點交易對後畫面會消失

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#912]
- 點交易對後畫面會消失

**Comment by TzuHanLiang** [comment]
- take 1hr

**Comment by Julian0701** [comment]
使用[TBETC000003](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000003_%E4%BD%BF%E7%94%A8%E8%80%85%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000003 使用者介面管理](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000003)驗證不通過

**Comment by Julian0701** [comment]
於[TBETC000003 使用者介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000003/20221104.md)驗證通過

**Comment by Julian0701** [comment]
v0.8.20.0+4.1 又發生 BCH/USDC 交易對無法顯示的問題

**Comment by Julian0701** [comment]
https://user-images.githubusercontent.com/114177573/202679340-d178e8ef-b902-4935-bd97-be82cf66f9d8.mov
註：清除暫存還是無法顯示，但訪客模式可以正常顯示

**Comment by TzuHanLiang** [comment]
take 1hrs

**Comment by Julian0701** [comment]
於 [TBETC000003](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000003/20221209.md) 驗證通過
