### ISSUE TITLE
[BUG] CancelOrder 邏輯調整

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#923]
- 有出現 用戶 cancel 但沒有紀錄到DB 得資料
- 優化 cancel Order 流程

**Comment by TzuHanLiang** [comment]
- take 5hrs
- remain
   - 驗證 rollback 是否有正確作用

**Comment by TzuHanLiang** [comment]
> * take 5hrs
> * remain
>   
>   * 驗證 rollback 是否有正確作用 1hr

- take 1hr 已驗證

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能檢驗](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221031.md)驗證通過
