### ISSUE TITLE
[DOC] 錯誤分析報告 - 用戶餘額更新錯誤

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#924]
- 提供錯誤分析報告
  - 錯誤分析
  - 錯誤原因
  - 修正辦法

- 只要分析新版上線後（2022/10/8） account 及 account_version 異常的情況
- account_id 1888325

**Comment by TzuHanLiang** [comment]
[doc](https://drophere.io/#receive/566475)

**Comment by TzuHanLiang** [comment]
- 程式碼遺留的部份
- 驗證 getAccountsByMemberId 加入 options 參數後是否有取得正確的 account
- 若出現 Database.OUTERTRADE_STATUS.DB_ORDER_DONE 錯誤，要到DB確認是否有生成對應的紀錄
- 驗證 rollback 是否有正確作用

**Comment by TzuHanLiang** [comment]
> * 程式碼遺留的部份
>   
>   * 驗證 getAccountsByMemberId 加入 options 參數後是否有取得正確的 account ~30mins
>   * 若出現 Database.OUTERTRADE_STATUS.DB_ORDER_DONE 錯誤，要到DB確認是否有生成對應的紀錄 ~1hrs
>   * 驗證 rollback 是否有正確作用 ~2hrs

- take 4hr 完成

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能檢驗](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221031.md)驗證通過
