### ISSUE TITLE
[UI][BUG] depthBook 出現腰帶

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#937]
- 左側orderbooks區域，在窗體很大時，出現大塊空白區

![Image](https://user-images.githubusercontent.com/17249354/196673442-ab2afbe8-3791-4990-8cae-1ba99bbbac6c.png)

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by Julian0701** [comment]
使用[TBETC000003](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000003_%E4%BD%BF%E7%94%A8%E8%80%85%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000003 使用者介面管理](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000003)驗證不通過

**Comment by TzuHanLiang** [comment]
<img width="822" alt="Screen Shot 2022-11-01 at 09 38 06" src="https://user-images.githubusercontent.com/17249354/199140163-ea4b333a-fc99-4b85-90a0-8cab8af99c4c.png">
@Luphia 是否可以知道最大的頁面尺寸？

**Comment by Luphia** [comment]
- There is no limit for page size
- The inner div element should always fit with container div

**Comment by Julian0701** [comment]
使用[TBETC000003](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000003_%E4%BD%BF%E7%94%A8%E8%80%85%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000003 使用者介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000003/20221111.md)驗證通過
