### ISSUE TITLE
[BUG] 市場選單在交易頁面放久後會不見

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#938]
- 有時頁面刷新即可恢復正常
- 但有時候要重開 server 才會恢復正常

**Comment by Luphia** [comment]
- 以下情況重新整理頁面即可恢復正常
![PHOTO-2022-10-20-15-38-52](https://user-images.githubusercontent.com/270062/196888102-6c5de3cd-9188-4496-89f4-c50a7b645102.jpg)
![PHOTO-2022-10-20-15-39-53](https://user-images.githubusercontent.com/270062/196888122-2bed9f30-3377-4456-84a5-ce099732ef8a.jpg)
![PHOTO-2022-10-20-15-40-14](https://user-images.githubusercontent.com/270062/196888132-db32e9ea-5e4f-4048-a390-3147c40fdb54.jpg)
![PHOTO-2022-10-20-15-40-31](https://user-images.githubusercontent.com/270062/196888143-a956db85-15c3-4339-8bfb-e0b344d797e6.jpg)

**Comment by Luphia** [comment]
- 偶發性 USDT 交易對中 BTC/USDT 或 ETH/USDT 會消失，另外開票處理

**Comment by TzuHanLiang** [comment]
- 出錯原因在剛重啟時為 TideBit pusher 推過來的ticker snapshot 裡面的 group 為 undefined，解決方法 formatTicker 時不要讓 pusher 傳過來的資料覆蓋掉被更新 ticker 的 group
-  另外開票處理 [#941](https://github.com/CAFECA-IO/TideBitEx/issues/941)

**Comment by Julian0701** [comment]
於[TBETC000006 交易界面的即時更新檢驗](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000003/20221028.md)驗證通過
