### ISSUE TITLE
[BUG] 市場選單裡的 btc/hkd 及 eth/hkd 交易對在某些情況下會不見

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#939]
- 在 analysis 做了某些操作後，會出現此情況

**Comment by TzuHanLiang** [comment]
- 解決方法同 #938

**Comment by Julian0701** [comment]
使用[TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000006_WebSocket%E7%95%B0%E5%B8%B8%E6%AA%A2%E9%A9%97.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000006 交易界面的即時更新檢驗](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000003/20221028.md)驗證通過
