### ISSUE TITLE
[BUG] 新增檢查餘額變化是否合理

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#946]
- 在新增 accountVersion 及更新 account 檢查：
  - 新 locked 的值要小於原本 account 的值
  - 新的 account 可用餘額要大於零
  - accountVersion 的 amount要大於零

若上訴任一條件不滿足 throw Error()

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能檢驗](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221031.md)驗證通過
