### ISSUE TITLE
[BUG] new.tidebit.com 出現有一用戶掛出高於自己可用餘額的委託單

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#948]
- 問題原因：
- DB 沒有檢查用戶是否有足夠的可用餘額
- 新增檢查機制 #946 
- 提供解決 sql
  - 1. 取消用戶多掛的委託單（兩筆）
  - 2. 新增兩筆取消掛單產生的 account_version
  - 3. 把錢還給用戶

**Comment by TzuHanLiang** [comment]
- 使用 #952 的流程把錢還給用戶
- take 1hr
- 強制 canceled 了用戶id為 4724 的三筆 order： 391839558、391356873、391357036

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能檢驗](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221031.md)驗證通過
