### ISSUE TITLE
[BUG] v0.8.17.2 hotfix ws error

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#955]
- 在 ExchangeHub 的 start 裡面啟動 ExchangeHubService.sync() 流程並 await 它導致 ws 異常

**Comment by TzuHanLiang** [comment]
- take 1hr

**Comment by TzuHanLiang** [comment]
- take 1hr

**Comment by Julian0701** [comment]
使用[TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000006_WebSocket%E7%95%B0%E5%B8%B8%E6%AA%A2%E9%A9%97.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000006 交易界面的即時更新檢驗](https://github.com/CAFECA-IO/Documents/tree/main/TBE/testresult/TBETC000003/20221028.md)驗證通過
