### ISSUE TITLE
[BUG][UI] MarketTrade 資產百分比按鈕功能錯誤

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#967]
### bid
- 使用若 price 有值則使用 price 若無則使用 selectedTicker.last 作為 price，將用戶 quoteAccount  / price * 百分比按鈕對應的百分比
### ask
- 直接將用戶 baseAccount * 百分比按鈕對應的百分比

### bid
- 使用 selectedTicker.last*1.05 作為 price，將用戶 quoteAccount  / price  * 百分比按鈕對應的百分比
### ask
- 直接將用戶 baseAccount * 百分比按鈕對應的百分比

**Comment by TzuHanLiang** [comment]
- take 1.5hr

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能
](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221104.md)驗證通過
