### ISSUE TITLE
[BUG][UI] MarketTrade 交易總金額要可以讓用戶輸入

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#968]
- 輸入total後
### bid
- 使用若 price 有值則使用 price 若無則使用 selectedTicker.last 作為 price，將用戶輸入的total  / price  得到可以買入多少 baseAccount currency
### ask
- 使用若 price 有值則使用 price 若無則使用 selectedTicker.last 作為 price，將用戶輸入的total  / price  得到需要賣出多少 baseAccount currency

### bid
- 使用 selectedTicker.last*1.1 作為 price，將用戶輸入的total  / price  得到可以買入多少 baseAccount currency
### ask
- 使用 selectedTicker.last*0.9 作為 price，將用戶輸入的total  / price  得到需要賣出多少 baseAccount currency

**Comment by TzuHanLiang** [comment]
take 1.5hr

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能
](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221104.md)驗證通過
