### ISSUE TITLE
[UI/UX] 管理介面需要能即時查詢 OKX 資料

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/TideBitEx#969]
- 營運人員需要稽核系統運作是否正常
- 需要即時檢視 OKX 上 TideBit 建立的委託單
- 需要即時檢視 30 日內 TideBit 在 OKX 上發生的所有交易行為
- 用於和 TideBit 內的記錄進行交叉比對

**Comment by JodieWu** [comment]
完成時間：2.5 hr
https://xd.adobe.com/view/a0164253-ea4b-442b-b8f2-469d79b68e28-f545/screen/576e8206-fc89-45b6-91bc-bcb5bae211df/

https://xd.adobe.com/view/a0164253-ea4b-442b-b8f2-469d79b68e28-f545/screen/10fa83c4-ff10-46bf-91ed-0db0b4c59437/
