### ISSUE TITLE
[BUG] 用戶將頁面放置一段時間後做交易有時會失敗，但是立即重新整理後一樣的交易就可以成功

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#972]
- 交易失敗的原因初步判定
  - 交易時刻新版登陸狀態與 TideBit-Lagacy 不一致

https://user-images.githubusercontent.com/17249354/198179254-f3abc717-e568-4c1f-be1c-3f3c5f80e1e5.MP4

**Comment by TzuHanLiang** [comment]
<img width="1680" alt="Screen Shot 2022-10-27 at 10 24 13" src="https://user-images.githubusercontent.com/17249354/198179300-33f5e421-b0c0-468d-b773-7eb01afca2a8.png">
<img width="1680" alt="Screen Shot 2022-10-27 at 10 37 35" src="https://user-images.githubusercontent.com/17249354/198179306-7d4ff810-76a0-4ccf-8f61-3ca96a6ce184.png">

**Comment by TzuHanLiang** [comment]
- take 5hr
- 加入倒計時 120 分鐘將用戶登出，新增 UI
- 若因為時間差照成無即時登出，交易欄位的確認按鈕也會因為用戶實際已登出而被 disabled

**Comment by Julian0701** [comment]
使用[TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000006_%E4%BA%A4%E6%98%93%E7%95%8C%E9%9D%A2%E7%9A%84%E5%8D%B3%E6%99%82%E6%9B%B4%E6%96%B0%E6%AA%A2%E9%A9%97.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000006 交易界面的即時更新](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000006/20221104.md
)驗證通過
