### ISSUE TITLE
[BUG] 在管理人員名單加入重複的用戶名和 Email 沒有挑出通知或阻擋機制

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBitEx#979]
- 測試環境
  - MacBook Pro
  - MacOS 13.0
  - Chrome

- 在管理員權限新增已有的用戶名會被直接加入
![image](https://user-images.githubusercontent.com/114177573/198523232-0b34bf43-2fa6-448e-8da7-81cd659a3e1a.png)
![image](https://user-images.githubusercontent.com/114177573/198524382-df166377-05d0-458c-8923-11f26a77d3fa.png)

- 新增已有的 Email 時，網頁會持續加載中
![image](https://user-images.githubusercontent.com/114177573/198525645-3e84de0b-9c7d-4a77-b89e-b784690a0cf6.png)

- 管理員加入重複的用戶名或 Email 時，應跳出「此用戶名已存在」或「此 Email 已有管理者權限」等通知，避免管理員加入重複的內容

**Comment by TzuHanLiang** [comment]
- take 1hr

**Comment by Julian0701** [comment]
使用[TBETC000002](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000002_%E7%AE%A1%E7%90%86%E6%AC%8A%E9%99%90%E5%B8%B3%E8%99%9F.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000002 管理權限帳號功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000002/20221104.md)驗證通過
