### ISSUE TITLE
[ENHANCE][後台管理介面] 稽核頁面調整-撮合成交紀錄

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#980]
#969 

- 頁面調整
- 更新 api
<img width="956" alt="Screen Shot 2022-10-31 at 18 12 16" src="https://user-images.githubusercontent.com/17249354/198984559-dbdb1e16-1b54-4e37-9653-ba82bb5924ab.png">

**Comment by TzuHanLiang** [comment]
- take 2hrs css 微調
- 解決 profit 走勢圖為 0 的錯誤
  - 錯誤原因為 getPrice 為 0

**Comment by TzuHanLiang** [comment]
- 排序不正確（api 回傳順序正確）

**Comment by TzuHanLiang** [comment]
- take 1hr

**Comment by Julian0701** [comment]
使用[TBETC000001](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000001_%E6%92%AE%E5%90%88%E6%88%90%E4%BA%A4%E7%B4%80%E9%8C%84%E6%9F%A5%E8%A9%A2.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000001 撮合成交紀錄查詢](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000001/20221104.md)驗證不通過

**Comment by Julian0701** [comment]
於[TBETC000001 撮合成交紀錄查詢](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000001/20221111.md)驗證不通過
