### ISSUE TITLE
[BUG] 出入金手續費的設定應再調整

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBitEx#985]
- 測試環境
  - MacBook Pro
  - MacOS 13.0
  - Chrome

- 設定出入金手續費時，無法輸入小於 0.1 的數字

![image](https://user-images.githubusercontent.com/114177573/198926219-5db496c9-94de-4538-8aee-b0d2e97a1881.png)

- 但可以設大於 100% 

![image](https://user-images.githubusercontent.com/114177573/198927493-f787120d-8123-41e2-bbe5-f5eac317d323.png)
![image](https://user-images.githubusercontent.com/114177573/198927524-4f691954-5f8d-4af5-946e-b1050b4d1090.png)

- 手續費的收取可能在 0.1% 以下，但應不可能大於 100%

**Comment by Luphia** [comment]
應具有以下限制：
最大值、最小值、最小刻度

**Comment by TzuHanLiang** [comment]
- take 1hrs

**Comment by Julian0701** [comment]
使用[TBETC000004](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000004_%E5%87%BA%E5%85%A5%E9%87%91%E6%89%8B%E7%BA%8C%E8%B2%BB%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000004 出入金手續費管理
](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000004/20221104.md)驗證通過
