### ISSUE TITLE
[ENHANCE] Tidebit 首頁做進 TidebitEx

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#986]
- 目的在於解決 #974 提出的issue

**Comment by TzuHanLiang** [comment]
- take 8 hrs
  - html outline
  - basic css
  - mostly i18n
  - partial rwd
- remain 5hrs
  - ticker trend chart will take  #2hrs
  - css 1hrs
  - rwd 1hrs
  - function & i18n

**Comment by TzuHanLiang** [comment]
- take 8hr
- remain 2hrs
  - ticker trend chart

**Comment by TzuHanLiang** [comment]
- remain:
  - TickerTrend 數字變化動畫
  - 手機見面 header

**Comment by TzuHanLiang** [comment]
- take 3hrs

**Comment by TzuHanLiang** [comment]
> * remain:
>   
>   * TickerTrend 數字變化動畫
>   * 手機介面 header

done

**Comment by Luphia** [comment]
- 數字動畫背景色需閃爍後沒有消失

![Image](https://user-images.githubusercontent.com/270062/203261368-7b0df583-0b2f-4714-8335-aaca68322240.gif)

- 元宇宙概念幣圖示替換並移除連結


![Image](https://user-images.githubusercontent.com/270062/203263373-86d2a2d7-2ed9-4279-b84b-7d1987d07c09.jpg)

**Comment by Luphia** [comment]
- 多語系選單滑鼠指標樣式
```css
cursor: pointer;
```

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by Julian0701** [comment]
使用 [TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000006_%E4%BA%A4%E6%98%93%E7%95%8C%E9%9D%A2%E7%9A%84%E5%8D%B3%E6%99%82%E6%9B%B4%E6%96%B0%E6%AA%A2%E9%A9%97.md) 驗證

**Comment by Julian0701** [comment]
於 [TBETC000006](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000006/20221125.md) 驗證不通過
放置一段時間後，交易市場的更新會落差，可見[螢幕錄製](https://drive.google.com/file/d/1Y0-rDeLtgKIiMmy3IsZ8w98kFQwG_zco/view?usp=share_link)的 7:18 - 8:45

**Comment by Luphia** [comment]
- 此票以功能實作為標的，更新速度問題另外開票追蹤
