### ISSUE TITLE
[BUG] 當前掛單紀錄查詢的顯示過濾出現錯誤

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/TideBitEx#987]
- 測試環境
  - MacBook Pro
  - MacOS 13.0
  - Chrome

- 點擊買入，列表呈現的卻是賣出，而且按鈕沒有變色
![image](https://user-images.githubusercontent.com/114177573/198944032-14fe032c-db4a-4923-865d-4c4cba5ff2c4.png)

- 選擇的按鈕應該像「全部」一樣變成深色
![image](https://user-images.githubusercontent.com/114177573/198944740-2d21ce1a-3512-44f0-81f3-cff8b8bd3f14.png)

**Comment by TzuHanLiang** [comment]
- take 1hrs

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
使用[TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20221104.md)驗證不通過
分類還是有誤

**Comment by Julian0701** [comment]
使用[TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000009_%E7%AE%A1%E7%90%86%E5%93%A1%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000009 管理員介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20221111.md)驗證不通過

**Comment by Julian0701** [comment]
於[TBETC000009 管理員介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20221125.md)驗證通過

**Comment by TzuHanLiang** [comment]
- take 2hrs
