### ISSUE TITLE
[ENHANCE][後台管理介面] 稽核頁面調整-當前掛單紀錄

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#989]
#969 

- 頁面調整
- 更新 api
- 
<img width="1028" alt="Screen Shot 2022-10-31 at 18 14 31" src="https://user-images.githubusercontent.com/17249354/198984979-61853796-1db4-464c-9dc6-6cab50a882cf.png">

**Comment by TzuHanLiang** [comment]
- take 3.5hrs

**Comment by TzuHanLiang** [comment]
- take 1hr sort

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
使用[TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20221104.md)驗證通過
