### ISSUE TITLE
[API requirement] need minSz for selectedTicker

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#99]
- post order will need to know `Minimum order size`
- 1 way is api add [getInstructments](https://www.okx.com/docs-v5/en/#rest-api-public-data-get-instruments)
- another is update getTickers reponse add new column minSz

**Comment by TzuHanLiang** [comment]
after finished this issue will need to check #90

**Comment by Waiting4Ever** [comment]
used 1 hr
