### ISSUE TITLE
[BUG] Tidebit database 跟 OKx 同一筆委託單紀錄的價格不一樣

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#991]
<img width="1292" alt="Screen Shot 2022-11-01 at 17 16 02" src="https://user-images.githubusercontent.com/17249354/199200771-8620b842-11ed-4b6f-9cbd-c4749fe9e23d.png">

**Comment by TzuHanLiang** [comment]
- take 3hr

**Comment by TzuHanLiang** [comment]
- 錯誤原因： 為了保證市價單一定會成功，所以前端在送市價單時會根據當時的市價，在買進的時候*1.05，賣出*0.95，在成完後沒有進行精度的修正導致的
- 過去的金額已無法調整，需檢查的是後續是否還有出現

**Comment by Julian0701** [comment]
於 [TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221209.md) 驗證通過
