### ISSUE TITLE
[BUG] 市場頁面市價單交易紀錄要顯示在 closed order 裡面

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#993]
- 沒有市場價格就直接顯示 [市場價]
- 或是用 database 裡面對應的 order資料計算撮合價格 
  - 買的話，就用 origin_locked 減去 locked 除以 funds_received
  - 賣的話，就用 funds_received 除以 origin_volume 減去 volume

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by Julian0701** [comment]
使用[TBETC000005](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000005_%E6%92%AE%E5%90%88%E4%BA%A4%E6%98%93%E5%8A%9F%E8%83%BD.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000005 撮合交易功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000005/20221111.md)驗證通過
