### ISSUE TITLE
[BUG] 只要新增為管理員即可訪問/analysis

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#994]
- 目前在某些情況即使有管理角色也無法訪問管理介面

**Comment by TzuHanLiang** [comment]
- take 1hr

**Comment by Julian0701** [comment]
使用[TBETC000002](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000002_%E7%AE%A1%E7%90%86%E6%AC%8A%E9%99%90%E5%B8%B3%E8%99%9F.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000007 管理權限帳號功能](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000002/20221104.md)驗證不通過

**Comment by Julian0701** [comment]
使用[TBETC000002](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000002_%E7%AE%A1%E7%90%86%E6%AC%8A%E9%99%90%E5%B8%B3%E8%99%9F.md)驗證
