### ISSUE TITLE
[BUG] /analysis 排版調整 - table 有些資料看不到

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBitEx#995]
<img width="838" alt="Screen Shot 2022-11-01 at 17 23 20" src="https://user-images.githubusercontent.com/17249354/199202094-5d7de6db-2514-43d0-84f6-e7838bab67cb.png">

**Comment by TzuHanLiang** [comment]
<img width="838" alt="Screen Shot 2022-11-01 at 17 23 56" src="https://user-images.githubusercontent.com/17249354/199202196-dfc260ef-c5e1-498d-be9c-62686cd084b8.png">

**Comment by TzuHanLiang** [comment]
take 3hrs

**Comment by Julian0701** [comment]
使用[TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testcases/TBETC000009_%E7%AE%A1%E7%90%86%E5%93%A1%E4%BB%8B%E9%9D%A2%E7%AE%A1%E7%90%86.md)驗證

**Comment by Julian0701** [comment]
使用[TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20221104.md)驗證不通過
支援幣種設定的畫面有問題，還有其他小錯誤

**Comment by Julian0701** [comment]
使用[TBETC000009](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20221104.md)驗證

**Comment by Julian0701** [comment]
於[TBETC000009 管理員介面管理](https://github.com/CAFECA-IO/Documents/blob/main/TBE/testresult/TBETC000009/20221111.md)驗證通過
